import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {UserPlus,Pencil,CheckCircle2,XCircle,UserX,Search,Loader2,Users2,ShieldCheck,Building2,Mail,Phone,CalendarDays,Clock,Camera,Briefcase,Landmark,Upload,KeyRound} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Badge} from '@/components/ui/badge';
import api from '@/lib/api';
import {toast} from 'sonner';

const EMPTY={full_name:'',email:'',password:'',role:'staff',departments:[],phone:'',birthday:'',telegram_id:'',punch_in_time:'10:30',grace_time:'00:10',punch_out_time:'19:00',profile_picture:'',joining_date:'',training_period_end:'',payroll_date:'',monthly_salary:'',employee_code:'',designation:'',department_id:'',reporting_manager_id:'',employment_type:'',confirmation_date:'',grade:'',cost_centre:'',pan_number:'',aadhaar_number:'',uan_number:'',pf_number:'',esic_number:'',bank_account_number:'',bank_name:'',ifsc_code:''};
const STATUS={active:['Active','bg-emerald-100 text-emerald-700'],pending_approval:['Pending approval','bg-amber-100 text-amber-700'],rejected:['Rejected','bg-red-100 text-red-700'],inactive:['Inactive','bg-slate-100 text-slate-600']};
const MODULES=[['can_access_taskosphere','Taskosphere'],['can_access_finix','Finix'],['can_access_compliance','Compliance'],['can_access_records','Records'],['can_access_proposals','Client Proposals'],['can_access_people_matrix','People Matrix']];
const DEPARTMENTS=['GST','IT','ACC','TDS','ROC','TM','MSME','FEMA','DSC','OTHER'];
const Field=({label,children})=><div className="space-y-1.5"><Label className="text-[11px] font-semibold tracking-widest text-slate-500 uppercase">{label}</Label>{children}</div>;
const Section=({icon:Icon,title,children})=><div className="border border-slate-200 bg-slate-50/50 p-4 space-y-4"><div className="flex items-center gap-2"><Icon className="h-3.5 w-3.5 text-[#1F6FB2]"/><span className="font-semibold text-sm text-[#0D3B66] uppercase tracking-wider">{title}</span></div>{children}</div>;
const readFileAsDataUrl=(file)=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});

export default function CompanyUserManager(){
 const [users,setUsers]=useState([]),[license,setLicense]=useState(null),[company,setCompany]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[editing,setEditing]=useState(null),[form,setForm]=useState(EMPTY),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[photoBusy,setPhotoBusy]=useState(false);
 const photoRef=useRef(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get('/commercial-master-data/users');setUsers(r.data?.users||[]);setLicense(r.data?.license||null);setCompany(r.data?.company||null)}catch(e){toast.error(e?.response?.data?.detail||'Failed to load company users')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const managers=useMemo(()=>users.filter(u=>u.role==='manager'&&u.status!=='rejected'),[users]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return users.filter(u=>(status==='all'||u.status===status)&&(!q||[u.full_name,u.email,u.phone,u.employee_code,u.designation,u.department_id,(u.departments||[]).join(' ')].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))))},[users,search,status]);
 const set=(k,v)=>setForm(p=>({...p,[k]:v}));
 const newUser=()=>{setEditing(null);setForm({...EMPTY,departments:[]});setOpen(true)};
 const edit=u=>{const f={...EMPTY};Object.keys(f).forEach(k=>f[k]=u[k]??f[k]);f.password='';f.departments=Array.isArray(u.departments)?u.departments:[];setEditing(u);setForm(f);setOpen(true)};
 const toggleDept=d=>set('departments',(form.departments||[]).includes(d)?form.departments.filter(x=>x!==d):[...(form.departments||[]),d]);
 const handlePhoto=async(e)=>{const file=e.target.files?.[0];if(!file)return;setPhotoBusy(true);try{const data=await readFileAsDataUrl(file);set('profile_picture',data);toast.success('Profile photo attached')}catch{toast.error('Could not read photo')}finally{setPhotoBusy(false);e.target.value=''}};
 const save=async()=>{if(!form.full_name.trim()||!form.email.trim())return toast.error('Full name and email are required');if(!editing&&form.password.length<8)return toast.error('Password must be at least 8 characters');setSaving(true);try{const p={...form,telegram_id:form.telegram_id?Number(form.telegram_id):null,monthly_salary:form.monthly_salary===''?null:Number(form.monthly_salary||0),departments:form.departments||[]};if(!p.password)delete p.password;if(editing)await api.put(`/commercial-master-data/users/${editing.id}`,p);else await api.post('/commercial-master-data/users',p);toast.success(editing?'User details updated':'User added — pending approval');setOpen(false);setEditing(null);setForm({...EMPTY});await load()}catch(e){toast.error(e?.response?.data?.detail||'Could not save user')}finally{setSaving(false)}};
 const action=async(u,a)=>{setBusy(u.id);try{await api.post(`/commercial-master-data/users/${u.id}/${a}`);toast.success(a==='approve'?'User approved':a==='reject'?'User rejected':'User deactivated');await load()}catch(e){toast.error(e?.response?.data?.detail||'Could not update user')}finally{setBusy(null)}};
 return <section id="users" className="border border-slate-200 bg-white overflow-hidden">
  <div className="px-5 py-4 border-b border-slate-100 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="p-2 bg-blue-50"><Users2 className="h-5 w-5 text-[#1F6FB2]"/></div><div><div className="flex items-center gap-2"><h2 className="text-sm font-bold text-slate-800">User Details &amp; Access</h2><Badge className="rounded-none bg-blue-50 text-[#1F6FB2] border-0 text-[10px]">{users.length}</Badge></div><p className="text-xs mt-1 text-slate-500">The same user master used by People Matrix. Add, edit, approve and deactivate users without leaving Admin.</p></div></div><Button onClick={newUser} className="h-9 rounded-none bg-[#0D3B66]"><UserPlus className="h-3.5 w-3.5 mr-1.5"/>Add User</Button></div>
  <div className="px-5 py-3 bg-slate-50 border-b border-slate-100 flex gap-3 items-center"><div className="relative flex-1"><Search className="h-4 w-4 absolute left-2.5 top-2.5 text-slate-400"/><Input className="pl-8 h-9 rounded-none bg-white" placeholder="Search name, email, phone, employee code…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-[155px] h-9 rounded-none bg-white"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem><SelectItem value="pending_approval">Pending approval</SelectItem><SelectItem value="active">Active</SelectItem><SelectItem value="rejected">Rejected</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select>{license&&<span className="text-[11px] font-semibold text-slate-500">Active: {users.filter(u=>u.status==='active').length} / {license.max_users}</span>}</div>
  {loading?<div className="py-12 flex justify-center"><Loader2 className="h-5 w-5 animate-spin text-slate-400"/></div>:visible.length===0?<div className="py-12 text-center text-sm text-slate-400">No users found.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50 border-b border-slate-200 text-left"><th className="px-4 py-3">User</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Departments / Designation</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody>{visible.map(u=><tr key={u.id} className="border-b border-slate-100 hover:bg-slate-50"><td className="px-4 py-3"><div className="font-semibold text-slate-800 flex items-center gap-2">{u.profile_picture?<img src={u.profile_picture} alt="" className="w-7 h-7 object-cover border border-slate-200"/>:null}{u.full_name||'—'}</div><div className="text-xs text-slate-500 flex items-center gap-1"><Mail className="h-3 w-3"/>{u.email}</div>{u.phone&&<div className="text-[11px] text-slate-400"><Phone className="h-3 w-3 inline mr-1"/>{u.phone}</div>}</td><td className="px-4 py-3"><Badge variant="outline" className="rounded-none capitalize">{u.role||'staff'}</Badge></td><td className="px-4 py-3 text-xs">{u.employee_code||'—'}<div className="text-[11px] text-slate-400">{u.employment_type||''}</div></td><td className="px-4 py-3 text-xs">{(u.departments||[]).join(', ')||u.department_id||'—'}<div className="text-[11px] text-slate-400">{u.designation||'—'}</div></td><td className="px-4 py-3"><Badge className={`border-0 text-[10px] ${STATUS[u.status]?.[1]||STATUS.inactive[1]}`}>{STATUS[u.status]?.[0]||'Inactive'}</Badge></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" className="h-8 w-8 rounded-none" onClick={()=>edit(u)} title="Edit"><Pencil className="h-3.5 w-3.5"/></Button>{u.status==='pending_approval'&&<><Button size="icon" variant="ghost" className="h-8 w-8 rounded-none text-emerald-600" disabled={busy===u.id} onClick={()=>action(u,'approve')} title="Approve"><CheckCircle2 className="h-4 w-4"/></Button><Button size="icon" variant="ghost" className="h-8 w-8 rounded-none text-red-500" disabled={busy===u.id} onClick={()=>action(u,'reject')} title="Reject"><XCircle className="h-4 w-4"/></Button></>}{u.status==='active'&&<Button size="icon" variant="ghost" className="h-8 w-8 rounded-none" disabled={busy===u.id} onClick={()=>action(u,'deactivate')} title="Deactivate"><UserX className="h-4 w-4"/></Button>}</div></td></tr>)}</tbody></table></div>}
  <div className="px-5 py-3 border-t border-slate-100 bg-slate-50/70 text-[11px] text-slate-500 flex gap-5 flex-wrap"><span className="flex items-center gap-1"><ShieldCheck className="h-3.5 w-3.5 text-emerald-600"/>Shared user master</span><span className="flex items-center gap-1"><Building2 className="h-3.5 w-3.5 text-[#1F6FB2]"/>{company?.name||'Licensed company'}</span><span>People Matrix and Admin use the same users collection</span></div>
  <Dialog open={open} onOpenChange={v=>{if(!v&&!saving){setOpen(false);setEditing(null)}}}><DialogContent className="max-w-5xl max-h-[92vh] overflow-y-auto rounded-none p-0"><div className="bg-[#0D3B66] text-white px-7 py-5"><div className="flex items-center gap-4"><div className="w-14 h-14 border-2 border-white/40 bg-white/10 flex items-center justify-center overflow-hidden">{form.profile_picture?<img src={form.profile_picture} alt="" className="w-full h-full object-cover"/>:<Camera className="h-6 w-6"/>}</div><div className="flex-1"><div className="text-[10px] font-bold tracking-widest uppercase text-blue-100">{editing?'Edit Member':'New Member'}</div><DialogTitle className="text-xl font-bold text-white">{editing?'Edit Team Member':'Add Team Member'}</DialogTitle><DialogDescription className="text-xs text-blue-100 mt-1">Same employee master and approval workflow used by People Matrix.</DialogDescription></div><input ref={photoRef} type="file" accept="image/*" className="hidden" onChange={handlePhoto}/><Button type="button" variant="outline" className="h-9 rounded-none bg-white/10 text-white border-white/30" disabled={photoBusy} onClick={()=>photoRef.current?.click()}><Upload className="h-3.5 w-3.5 mr-1.5"/>{photoBusy?'Reading…':'Upload Photo'}</Button></div></div>
   <div className="p-6 space-y-5">
    <Section icon={KeyRound} title="Account Details"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><Field label="Full Name *"><Input className="h-10 rounded-none" value={form.full_name} onChange={e=>set('full_name',e.target.value)}/></Field><Field label="Email Address *"><Input className="h-10 rounded-none" type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></Field><Field label="Phone Number"><Input className="h-10 rounded-none" value={form.phone} onChange={e=>set('phone',e.target.value)}/></Field><Field label={editing?'New Password (optional)':'Initial Password *'}><Input className="h-10 rounded-none" type="password" value={form.password} onChange={e=>set('password',e.target.value)}/></Field></div></Section>
    <Section icon={Users2} title="Department & Role"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Role"><Select value={form.role} onValueChange={v=>set('role',v)}><SelectTrigger className="h-10 rounded-none"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="staff">User / Staff</SelectItem><SelectItem value="manager">Manager</SelectItem></SelectContent></Select></Field><Field label="Primary Department"><Input className="h-10 rounded-none" value={form.department_id} onChange={e=>set('department_id',e.target.value)}/></Field><Field label="Reporting Manager"><Select value={form.reporting_manager_id||'__none__'} onValueChange={v=>set('reporting_manager_id',v==='__none__'?'':v)}><SelectTrigger className="h-10 rounded-none"><SelectValue placeholder="None"/></SelectTrigger><SelectContent><SelectItem value="__none__">None</SelectItem>{managers.filter(m=>m.id!==editing?.id).map(m=><SelectItem key={m.id} value={m.id}>{m.full_name||m.email}</SelectItem>)}</SelectContent></Select></Field></div><div><Label className="text-[11px] font-semibold tracking-widest text-slate-500 uppercase">Department Access</Label><div className="flex flex-wrap gap-2 mt-2">{DEPARTMENTS.map(d=><button key={d} type="button" onClick={()=>toggleDept(d)} className={`px-3 py-2 border text-xs font-semibold rounded-none ${(form.departments||[]).includes(d)?'bg-[#0D3B66] text-white border-[#0D3B66]':'bg-white text-slate-600 border-slate-300'}`}>{d}</button>)}</div></div></Section>
    <Section icon={Clock} title="Work Shift Schedule"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Punch In"><Input type="time" className="h-10 rounded-none" value={form.punch_in_time} onChange={e=>set('punch_in_time',e.target.value)}/></Field><Field label="Grace Period"><Input type="time" className="h-10 rounded-none" value={form.grace_time} onChange={e=>set('grace_time',e.target.value)}/></Field><Field label="Punch Out"><Input type="time" className="h-10 rounded-none" value={form.punch_out_time} onChange={e=>set('punch_out_time',e.target.value)}/></Field></div></Section>
    <Section icon={CalendarDays} title="Personal Details"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Birthday"><Input type="date" className="h-10 rounded-none" value={form.birthday} onChange={e=>set('birthday',e.target.value)}/></Field><Field label="Telegram ID"><Input type="number" className="h-10 rounded-none" value={form.telegram_id} onChange={e=>set('telegram_id',e.target.value)}/></Field><Field label="Designation"><Input className="h-10 rounded-none" value={form.designation} onChange={e=>set('designation',e.target.value)}/></Field></div></Section>
    <Section icon={Briefcase} title="Employment Details"><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Field label="Joining Date"><Input type="date" className="h-10 rounded-none" value={form.joining_date} onChange={e=>set('joining_date',e.target.value)}/></Field><Field label="Training / Probation End"><Input type="date" className="h-10 rounded-none" value={form.training_period_end} onChange={e=>set('training_period_end',e.target.value)}/></Field><Field label="Confirmation Date"><Input type="date" className="h-10 rounded-none" value={form.confirmation_date} onChange={e=>set('confirmation_date',e.target.value)}/></Field><Field label="Payroll Date"><Input type="date" className="h-10 rounded-none" value={form.payroll_date} onChange={e=>set('payroll_date',e.target.value)}/></Field><Field label="Employee Code"><Input className="h-10 rounded-none" value={form.employee_code} onChange={e=>set('employee_code',e.target.value)}/></Field><Field label="Employment Type"><Select value={form.employment_type||'__none__'} onValueChange={v=>set('employment_type',v==='__none__'?'':v)}><SelectTrigger className="h-10 rounded-none"><SelectValue placeholder="Not set"/></SelectTrigger><SelectContent>{['__none__','full_time','part_time','contract','intern'].map(v=><SelectItem key={v} value={v}>{v==='__none__'?'Not set':v.replace('_',' ')}</SelectItem>)}</SelectContent></Select></Field><Field label="Grade"><Input className="h-10 rounded-none" value={form.grade} onChange={e=>set('grade',e.target.value)}/></Field><Field label="Cost Centre"><Input className="h-10 rounded-none" value={form.cost_centre} onChange={e=>set('cost_centre',e.target.value)}/></Field><Field label="Monthly Salary (₹)"><Input type="number" className="h-10 rounded-none" value={form.monthly_salary} onChange={e=>set('monthly_salary',e.target.value)}/></Field></div></Section>
    <Section icon={ShieldCheck} title="Attendance & Statutory Details"><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Field label="PAN"><Input className="h-10 rounded-none" value={form.pan_number} onChange={e=>set('pan_number',e.target.value.toUpperCase())}/></Field><Field label="Aadhaar"><Input className="h-10 rounded-none" value={form.aadhaar_number} onChange={e=>set('aadhaar_number',e.target.value)}/></Field><Field label="UAN"><Input className="h-10 rounded-none" value={form.uan_number} onChange={e=>set('uan_number',e.target.value)}/></Field><Field label="PF Number"><Input className="h-10 rounded-none" value={form.pf_number} onChange={e=>set('pf_number',e.target.value)}/></Field><Field label="ESIC Number"><Input className="h-10 rounded-none" value={form.esic_number} onChange={e=>set('esic_number',e.target.value)}/></Field></div></Section>
    <Section icon={Landmark} title="Bank Details"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Bank Account Number"><Input className="h-10 rounded-none" value={form.bank_account_number} onChange={e=>set('bank_account_number',e.target.value)}/></Field><Field label="Bank Name"><Input className="h-10 rounded-none" value={form.bank_name} onChange={e=>set('bank_name',e.target.value)}/></Field><Field label="IFSC Code"><Input className="h-10 rounded-none" value={form.ifsc_code} onChange={e=>set('ifsc_code',e.target.value.toUpperCase())}/></Field></div></Section>
    <Section icon={ShieldCheck} title="Licensed Module Access"><p className="text-xs text-slate-500">People Matrix uses the same permissions document. Master Data never grants a module outside the company license.</p><div className="grid grid-cols-2 md:grid-cols-3 gap-2">{MODULES.map(([key,label])=><div key={key} className="border border-slate-200 bg-white px-3 py-3"><div className="text-xs font-semibold text-slate-700">{label}</div><div className="text-[10px] mt-1 font-bold text-emerald-600">{form?.permissions?.[key]?'Enabled':(license?.modules||[]).some(m=>String(m).toLowerCase().replace(/\s+/g,'_')===label.toLowerCase().replace(/\s+/g,'_'))?'Licensed':'Controlled by license'}</div></div>)}</div></Section>
   </div>
   <div className="border-t border-slate-200 px-6 py-4 flex justify-end gap-2"><Button variant="ghost" className="h-10 rounded-none" onClick={()=>setOpen(false)} disabled={saving}>Cancel</Button><Button className="h-10 rounded-none bg-[#0D3B66]" onClick={save} disabled={saving}>{saving?<Loader2 className="h-4 w-4 mr-2 animate-spin"/>:<UserPlus className="h-4 w-4 mr-2"/>}{editing?'Save Changes':'Create User'}</Button></div>
  </DialogContent></Dialog>
 </section>;
}
