import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Plus, Pencil, Search, Loader2, Users2, Building2, MapPin, FileCheck, Shield, Trash2, X, Download, Upload, FileDown, FileText, Sparkles, UserCheck, BriefcaseBusiness } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import api from '@/lib/api';
import { toast } from 'sonner';

const TYPES=[['proprietor','Proprietor'],['pvt_ltd','Private Limited'],['llp','LLP'],['public_ltd','Public Limited'],['section_8','Section 8 Company'],['partnership','Partnership'],['huf','HUF'],['trust','Trust'],['other','Other']];
const SERVICES=['GST','Trademark','Income Tax','ROC','Audit','Compliance','Company Registration','Tax Planning','Accounting','Payroll','Other'];
const EMPTY={company_name:'',client_type:'proprietor',client_type_other:'',contact_persons:[{name:'',email:'',phone:'',designation:'',birthday:'',din:''}],email:'',phone:'',birthday:'',address:'',city:'',state:'',pincode:'',services:[],dsc_details:[],assignments:[],notes:'',status:'active',referred_by:'',auditor:'',gstin:'',pan:'',gst_treatment:'regular',place_of_supply:'',default_payment_terms:'Due on receipt',credit_limit:'',opening_balance:'',opening_balance_type:'Dr',tally_ledger_name:'',tally_group:'Sundry Debtors',website:'',msme_number:'',gst_address:'',gst_city:'',gst_state:'',gst_pin:'',cin:'',llpin:'',proprietor_name:'',mca_fetch_date:''};
const EMPTY_DSC={certificate_number:'',holder_name:'',issue_date:'',expiry_date:'',notes:''};
const EMPTY_ASSIGNMENT={user_id:'',services:[]};
const Field=({label,children})=><div className="space-y-1.5"><Label className="text-[11px] font-semibold tracking-wide text-slate-600 uppercase">{label}</Label>{children}</div>;
const input='h-10 rounded-none';
const Section=({icon:Icon,title,children})=><div className="border border-slate-200 p-5 space-y-4"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-[#1F6FB2]"/><span className="font-bold text-sm uppercase tracking-wider text-slate-700">{title}</span></div>{children}</div>;

function normalizeParsed(data){const d=data?.data||data?.parsed||data||{};const out={};const map={name:'company_name',company_name:'company_name',legal_name:'company_name',constitution:'client_type',client_type:'client_type',email:'email',phone:'phone',mobile:'phone',address:'address',registered_address:'address',city:'city',state:'state',pincode:'pincode',pin:'pincode',gstin:'gstin',gst_number:'gstin',pan:'pan',website:'website',cin:'cin',llpin:'llpin',proprietor_name:'proprietor_name',msme_number:'msme_number',udyam_number:'msme_number',mca_fetch_date:'mca_fetch_date',gst_treatment:'gst_treatment',place_of_supply:'place_of_supply'};Object.entries(map).forEach(([from,to])=>{if(d[from]!=null&&d[from]!=='')out[to]=d[from]});const type=String(out.client_type||'').toLowerCase().replace(/[\s-]+/g,'_');const aliases={private_limited:'pvt_ltd',private_limited_company:'pvt_ltd',pvt_ltd:'pvt_ltd',limited_liability_partnership:'llp',llp:'llp',public_limited:'public_ltd',section_8_company:'section_8',proprietorship:'proprietor',proprietor:'proprietor'};if(aliases[type])out.client_type=aliases[type];return out;}

export default function MasterDataClientManager(){
 const [clients,setClients]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(EMPTY),[search,setSearch]=useState(''),[open,setOpen]=useState(false),[users,setUsers]=useState([]),[importing,setImporting]=useState(false),[docBusy,setDocBusy]=useState(false),[docFiles,setDocFiles]=useState({gst:null,udyam:null,mca:null});
 const csvInputRef=useRef(null);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get('/clients');setClients(Array.isArray(r.data)?r.data:(r.data?.clients||[]));}catch(e){toast.error(e?.response?.data?.detail||'Failed to load clients')}finally{setLoading(false)}},[]);
 const loadUsers=useCallback(async()=>{try{const r=await api.get('/commercial-master-data/users');setUsers(r.data?.users||[])}catch{setUsers([])}},[]);
 useEffect(()=>{load();loadUsers()},[load,loadUsers]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return clients.filter(c=>!q||[c.company_name,c.email,c.phone,c.gstin,c.pan,c.city,c.state].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))},[clients,search]);
 const set=(k,v)=>setForm(p=>({...p,[k]:v}));
 const openNew=()=>{setEditing(null);setForm(JSON.parse(JSON.stringify(EMPTY)));setDocFiles({gst:null,udyam:null,mca:null});setOpen(true)};
 const openEdit=c=>{setEditing(c);setForm({...EMPTY,...c,contact_persons:Array.isArray(c.contact_persons)&&c.contact_persons.length?c.contact_persons.map(x=>({...x,birthday:x.birthday?.slice?.(0,10)||x.birthday||'',din:x.din||''})):JSON.parse(JSON.stringify(EMPTY.contact_persons)),dsc_details:Array.isArray(c.dsc_details)?c.dsc_details.map(x=>({...x,issue_date:x.issue_date?.slice?.(0,10)||'',expiry_date:x.expiry_date?.slice?.(0,10)||''})):[],assignments:Array.isArray(c.assignments)?c.assignments:[],services:Array.isArray(c.services)?c.services:[]});setDocFiles({gst:null,udyam:null,mca:null});setOpen(true)};
 const close=()=>{if(!saving&&!docBusy){setOpen(false);setEditing(null)}};
 const save=async()=>{if(!form.company_name.trim())return toast.error('Client / company name is required');setSaving(true);try{const payload={...form,company_name:form.company_name.trim(),gstin:form.gstin?.trim().toUpperCase()||null,pan:form.pan?.trim().toUpperCase()||null,contact_persons:(form.contact_persons||[]).filter(x=>x.name?.trim()).map(x=>({...x,name:x.name.trim(),birthday:x.birthday||null,din:x.din?.trim()||null})),services:form.services||[],dsc_details:(form.dsc_details||[]).map(x=>({...x,certificate_number:x.certificate_number?.trim()||'',holder_name:x.holder_name?.trim()||'',notes:x.notes?.trim()||null})),assignments:(form.assignments||[]).filter(a=>a.user_id).map(a=>({user_id:a.user_id,services:a.services||[]}))};if(editing)await api.put(`/clients/${editing.id}`,payload);else await api.post('/clients',payload);toast.success(editing?'Client updated':'Client added to shared client master');close();await load()}catch(e){const d=e?.response?.data?.detail;toast.error(Array.isArray(d)?d.map(x=>x.msg).join(' | '):(d||'Could not save client'))}finally{setSaving(false)}};
 const toggleService=s=>set('services',(form.services||[]).includes(s)?form.services.filter(x=>x!==s):[...(form.services||[]),s]);
 const setContact=(i,k,v)=>set('contact_persons',(form.contact_persons||[]).map((c,n)=>n===i?{...c,[k]:v}:c));
 const addContact=()=>set('contact_persons',[...(form.contact_persons||[]),{name:'',email:'',phone:'',designation:'',birthday:'',din:''}]);
 const removeContact=i=>set('contact_persons',(form.contact_persons||[]).filter((_,n)=>n!==i));
 const addDSC=()=>set('dsc_details',[...(form.dsc_details||[]),{...EMPTY_DSC}]);
 const updateDSC=(i,k,v)=>set('dsc_details',(form.dsc_details||[]).map((d,n)=>n===i?{...d,[k]:v}:d));
 const removeDSC=i=>set('dsc_details',(form.dsc_details||[]).filter((_,n)=>n!==i));
 const addAssignment=()=>set('assignments',[...(form.assignments||[]),{...EMPTY_ASSIGNMENT}]);
 const updateAssignment=(i,k,v)=>set('assignments',(form.assignments||[]).map((a,n)=>n===i?{...a,[k]:v}:a));
 const toggleAssignmentService=(i,s)=>set('assignments',(form.assignments||[]).map((a,n)=>n===i?{...a,services:(a.services||[]).includes(s)?a.services.filter(x=>x!==s):[...(a.services||[]),s]}:a));
 const removeAssignment=i=>set('assignments',(form.assignments||[]).filter((_,n)=>n!==i));
 const applyParsed=data=>{const parsed=normalizeParsed(data);setForm(p=>({...p,...parsed}));toast.success('Document data applied to the client form')};
 const analyzeDocs=async()=>{const files=Object.values(docFiles).filter(Boolean);if(!files.length)return toast.error('Select GST, Udyam or MCA master-data documents first');setDocBusy(true);try{const fd=new FormData();files.forEach(f=>fd.append('files',f));const r=await api.post('/clients/parse-multi-documents',fd,{headers:{'Content-Type':'multipart/form-data'}});applyParsed(r.data)}catch(e){toast.error(e?.response?.data?.detail||'Could not read the uploaded documents')}finally{setDocBusy(false)}};
 const importMds=async(file)=>{if(!file)return;setDocBusy(true);try{const fd=new FormData();fd.append('file',file);const r=await api.post('/clients/parse-mds-excel',fd,{headers:{'Content-Type':'multipart/form-data'}});applyParsed(r.data)}catch(e){toast.error(e?.response?.data?.detail||'Could not read the master-data Excel file')}finally{setDocBusy(false)}};
 const downloadTemplate=()=>{const headers=['company_name','client_type','email','phone','birthday','address','city','state','pincode','gstin','pan','gst_treatment','place_of_supply','default_payment_terms','credit_limit','opening_balance','opening_balance_type','tally_ledger_name','tally_group','website','msme_number','cin','llpin','proprietor_name','services','notes'];const csv=headers.join(',')+'\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='client_master_template.csv';a.click();URL.revokeObjectURL(url)};
 const exportCsv=()=>{const headers=['Company Name','Constitution','GSTIN','PAN','Email','Phone','City','State','Services','Status'];const rows=[headers,...clients.map(c=>[c.company_name||'',TYPES.find(x=>x[0]===c.client_type)?.[1]||c.client_type||'',c.gstin||'',c.pan||'',c.email||'',c.phone||'',c.city||'',c.state||'',(c.services||[]).join('; '),c.status||''])];const csv=rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`clients_export_${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)};
 const handleImportCSV=async(e)=>{const file=e.target.files?.[0];if(!file)return;setImporting(true);try{const fd=new FormData();fd.append('file',file);const r=await api.post('/clients/import',fd,{headers:{'Content-Type':'multipart/form-data'}});toast.success(r.data?.message||`${r.data?.clients_created||0} clients imported`);await load()}catch(err){toast.error(err?.response?.data?.detail||'Import failed')}finally{setImporting(false);e.target.value=''}};
 return <section id="clients" className="border border-slate-200 bg-white overflow-hidden">
  <div className="master-data-blue-header"><div className="flex items-center gap-3"><div className="master-data-blue-header-icon"><Building2/></div><div><div className="flex items-center gap-2"><h2 className="text-sm font-bold">Client Details &amp; Access</h2><span className="master-data-blue-header-badge px-2 py-0.5 text-[10px] font-bold">{clients.length}</span></div><p className="text-xs mt-1">Same client master used by Records, Quotations, Invoicing, Compliance and Client Proposals.</p></div></div><div className="master-data-blue-header-actions"><input ref={csvInputRef} type="file" accept=".csv,.xlsx,.xls" className="hidden" onChange={handleImportCSV}/><Button variant="outline" className="h-9 rounded-none master-data-blue-header-btn-outline" onClick={downloadTemplate}><FileDown className="h-3.5 w-3.5 mr-1.5"/>Template</Button><Button variant="outline" className="h-9 rounded-none master-data-blue-header-btn-outline" disabled={importing} onClick={()=>csvInputRef.current?.click()}>{importing?<Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin"/>:<Upload className="h-3.5 w-3.5 mr-1.5"/>}Bulk Import</Button><Button variant="outline" className="h-9 rounded-none master-data-blue-header-btn-outline" disabled={!clients.length} onClick={exportCsv}><Download className="h-3.5 w-3.5 mr-1.5"/>Export</Button><Button onClick={openNew} className="h-9 rounded-none master-data-blue-header-btn-solid"><Plus className="h-3.5 w-3.5 mr-1.5"/>Add Client</Button></div></div>
  <div className="px-5 py-3 bg-slate-50 border-b border-slate-100 flex items-center gap-3"><div className="relative flex-1"><Search className="h-4 w-4 absolute left-2.5 top-2.5 text-slate-400"/><Input className="pl-8 h-9 rounded-none bg-white" placeholder="Search client, GSTIN, PAN, phone, email…" value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="text-[11px] font-semibold text-slate-500">{visible.length} shown</span></div>
  {loading?<div className="py-12 flex justify-center"><Loader2 className="h-5 w-5 animate-spin text-slate-400"/></div>:visible.length===0?<div className="py-12 text-center text-sm text-slate-400">No clients found. Add a client here or create one from Records.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50 border-b border-slate-200 text-left"><th className="px-4 py-3">Client</th><th className="px-4 py-3">Constitution</th><th className="px-4 py-3">GSTIN / PAN</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Services</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody>{visible.map(c=><tr key={c.id} className="border-b border-slate-100 hover:bg-slate-50/70"><td className="px-4 py-3"><div className="font-semibold text-slate-800">{c.company_name||'—'}</div><div className="text-[11px] text-slate-400">{c.city||''}{c.state?` · ${c.state}`:''}</div></td><td className="px-4 py-3 text-xs text-slate-600">{TYPES.find(x=>x[0]===c.client_type)?.[1]||c.client_type||'—'}</td><td className="px-4 py-3 text-xs text-slate-600">{c.gstin||'—'}<div className="text-[11px] text-slate-400">{c.pan||'—'}</div></td><td className="px-4 py-3 text-xs text-slate-600">{c.email||'—'}<div>{c.phone||''}</div></td><td className="px-4 py-3 text-xs text-slate-600">{(c.services||[]).slice(0,3).join(', ')||'—'}{(c.services||[]).length>3?'…':''}</td><td className="px-4 py-3 text-right"><Button size="icon" variant="ghost" className="h-8 w-8 rounded-none" onClick={()=>openEdit(c)} title="Edit client"><Pencil className="h-3.5 w-3.5"/></Button></td></tr>)}</tbody></table></div>}
  <div className="px-5 py-3 border-t border-slate-100 bg-slate-50/70 text-[11px] text-slate-500 flex flex-wrap gap-5"><span>Shared /clients collection</span><span>Records and Master Data edit the same client</span><span>Quotation client picker reads the same master</span></div>
  {open&&<div className="fixed inset-0 z-[100] bg-slate-900/50 flex items-center justify-center p-4"><div className="w-full max-w-6xl max-h-[94vh] overflow-y-auto bg-white border border-slate-200 shadow-2xl">
    <div className="sticky top-0 z-20 bg-[#0D3B66] text-white px-6 py-5 flex items-center justify-between"><div><div className="text-[10px] font-bold tracking-widest uppercase text-blue-200">Client Master / Records-compatible form</div><h3 className="text-xl font-bold">{editing?'Edit Client Profile':'New Client Profile'}</h3><p className="text-xs text-blue-100 mt-1">All client fields, document auto-fill, assignments, DSC and billing data stay on the same client record.</p></div><Button variant="ghost" size="icon" className="h-9 w-9 rounded-none text-white hover:bg-white/10" onClick={close}><X className="h-5 w-5"/></Button></div>
    <div className="p-6 space-y-5">
      <Section icon={Building2} title="Client Information"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Client / Company Name *"><Input className={input} value={form.company_name||''} onChange={e=>set('company_name',e.target.value)}/></Field><Field label="Constitution"><Select value={form.client_type||'proprietor'} onValueChange={v=>set('client_type',v)}><SelectTrigger className={input}><SelectValue/></SelectTrigger><SelectContent>{TYPES.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></Field><Field label="Other Constitution"><Input className={input} value={form.client_type_other||''} onChange={e=>set('client_type_other',e.target.value)}/></Field><Field label="Email"><Input className={input} type="email" value={form.email||''} onChange={e=>set('email',e.target.value)}/></Field><Field label="Phone"><Input className={input} value={form.phone||''} onChange={e=>set('phone',e.target.value)}/></Field><Field label="Birthday"><Input className={input} type="date" value={form.birthday||''} onChange={e=>set('birthday',e.target.value)}/></Field><Field label="Website"><Input className={input} value={form.website||''} onChange={e=>set('website',e.target.value)}/></Field><Field label="Referred By"><Input className={input} value={form.referred_by||''} onChange={e=>set('referred_by',e.target.value)}/></Field><Field label="Auditor"><Input className={input} value={form.auditor||''} onChange={e=>set('auditor',e.target.value)}/></Field></div></Section>
      <Section icon={FileText} title="Upload Master Data / Auto-fill"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><label className="border border-dashed border-slate-300 p-4 cursor-pointer hover:bg-slate-50"><div className="text-xs font-bold">GST Certificate</div><div className="text-[10px] text-slate-400 mt-1">PDF</div><input type="file" accept=".pdf" className="hidden" onChange={e=>setDocFiles(p=>({...p,gst:e.target.files?.[0]||null}))}/><div className="text-[10px] text-[#1F6FB2] mt-2 truncate">{docFiles.gst?.name||'Choose file'}</div></label><label className="border border-dashed border-slate-300 p-4 cursor-pointer hover:bg-slate-50"><div className="text-xs font-bold">Udyam Certificate</div><div className="text-[10px] text-slate-400 mt-1">PDF</div><input type="file" accept=".pdf" className="hidden" onChange={e=>setDocFiles(p=>({...p,udyam:e.target.files?.[0]||null}))}/><div className="text-[10px] text-[#1F6FB2] mt-2 truncate">{docFiles.udyam?.name||'Choose file'}</div></label><label className="border border-dashed border-slate-300 p-4 cursor-pointer hover:bg-slate-50"><div className="text-xs font-bold">MCA Master Data</div><div className="text-[10px] text-slate-400 mt-1">PDF / XLSX</div><input type="file" accept=".pdf,.xlsx,.xls" className="hidden" onChange={e=>setDocFiles(p=>({...p,mca:e.target.files?.[0]||null}))}/><div className="text-[10px] text-[#1F6FB2] mt-2 truncate">{docFiles.mca?.name||'Choose file'}</div></label></div><div className="flex flex-wrap gap-2"><Button type="button" className="h-9 rounded-none bg-[#1F6FB2]" onClick={analyzeDocs} disabled={docBusy}>{docBusy?<Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin"/>:<Sparkles className="h-3.5 w-3.5 mr-1.5"/>}Read &amp; Auto-fill</Button><label className="inline-flex"><input type="file" accept=".xlsx,.xls" className="hidden" onChange={e=>importMds(e.target.files?.[0])}/><Button type="button" variant="outline" className="h-9 rounded-none" asChild><span><Upload className="h-3.5 w-3.5 mr-1.5"/>Upload Master Data Excel</span></Button></label></div></Section>
      <Section icon={Users2} title="Contact Persons"><div className="flex justify-end -mt-2"><Button type="button" size="sm" variant="outline" className="rounded-none h-9" onClick={addContact}><Plus className="h-3.5 w-3.5 mr-1"/>Add Contact</Button></div>{(form.contact_persons||[]).map((c,i)=><div key={i} className="grid grid-cols-1 md:grid-cols-6 gap-3 border-b border-slate-100 pb-4 mb-4 last:border-0"><Field label="Name"><Input className={input} value={c.name||''} onChange={e=>setContact(i,'name',e.target.value)}/></Field><Field label="Email"><Input className={input} value={c.email||''} onChange={e=>setContact(i,'email',e.target.value)}/></Field><Field label="Phone"><Input className={input} value={c.phone||''} onChange={e=>setContact(i,'phone',e.target.value)}/></Field><Field label="Designation"><Input className={input} value={c.designation||''} onChange={e=>setContact(i,'designation',e.target.value)}/></Field><Field label="Birthday"><Input className={input} type="date" value={c.birthday||''} onChange={e=>setContact(i,'birthday',e.target.value)}/></Field><Field label="DIN"><Input className={input} value={c.din||''} onChange={e=>setContact(i,'din',e.target.value)}/></Field><Button type="button" variant="ghost" className="h-9 rounded-none text-red-600 md:col-span-6" disabled={(form.contact_persons||[]).length===1} onClick={()=>removeContact(i)}><Trash2 className="h-4 w-4 mr-1"/>Remove contact</Button></div>)}</Section>
      <Section icon={MapPin} title="Primary & GST Address"><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Field label="Address"><Textarea className="rounded-none min-h-[82px]" value={form.address||''} onChange={e=>set('address',e.target.value)}/></Field><Field label="City"><Input className={input} value={form.city||''} onChange={e=>set('city',e.target.value)}/></Field><Field label="State"><Input className={input} value={form.state||''} onChange={e=>set('state',e.target.value)}/></Field><Field label="PIN Code"><Input className={input} value={form.pincode||''} onChange={e=>set('pincode',e.target.value)}/></Field><Field label="GST Registered Address"><Textarea className="rounded-none min-h-[82px]" value={form.gst_address||''} onChange={e=>set('gst_address',e.target.value)}/></Field><Field label="GST City"><Input className={input} value={form.gst_city||''} onChange={e=>set('gst_city',e.target.value)}/></Field><Field label="GST State"><Input className={input} value={form.gst_state||''} onChange={e=>set('gst_state',e.target.value)}/></Field><Field label="GST PIN"><Input className={input} value={form.gst_pin||''} onChange={e=>set('gst_pin',e.target.value)}/></Field></div></Section>
      <Section icon={FileCheck} title="Tax & Billing"><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Field label="GSTIN"><Input className={input} value={form.gstin||''} onChange={e=>set('gstin',e.target.value.toUpperCase())}/></Field><Field label="PAN"><Input className={input} value={form.pan||''} onChange={e=>set('pan',e.target.value.toUpperCase())}/></Field><Field label="GST Treatment"><Select value={form.gst_treatment||'regular'} onValueChange={v=>set('gst_treatment',v)}><SelectTrigger className={input}><SelectValue/></SelectTrigger><SelectContent>{['regular','composition','unregistered','consumer','overseas'].map(v=><SelectItem key={v} value={v}>{v.replace('_',' ')}</SelectItem>)}</SelectContent></Select></Field><Field label="Place of Supply"><Input className={input} value={form.place_of_supply||''} onChange={e=>set('place_of_supply',e.target.value)}/></Field><Field label="Payment Terms"><Input className={input} value={form.default_payment_terms||''} onChange={e=>set('default_payment_terms',e.target.value)}/></Field><Field label="Credit Limit"><Input className={input} type="number" value={form.credit_limit||''} onChange={e=>set('credit_limit',e.target.value)}/></Field><Field label="Opening Balance"><Input className={input} type="number" value={form.opening_balance||''} onChange={e=>set('opening_balance',e.target.value)}/></Field><Field label="Balance Type"><Select value={form.opening_balance_type||'Dr'} onValueChange={v=>set('opening_balance_type',v)}><SelectTrigger className={input}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Dr">Dr</SelectItem><SelectItem value="Cr">Cr</SelectItem></SelectContent></Select></Field></div></Section>
      <Section icon={BriefcaseBusiness} title="Company / Registration Details"><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Field label="CIN"><Input className={input} value={form.cin||''} onChange={e=>set('cin',e.target.value.toUpperCase())}/></Field><Field label="LLPIN"><Input className={input} value={form.llpin||''} onChange={e=>set('llpin',e.target.value.toUpperCase())}/></Field><Field label="Proprietor Name"><Input className={input} value={form.proprietor_name||''} onChange={e=>set('proprietor_name',e.target.value)}/></Field><Field label="MSME / Udyam No."><Input className={input} value={form.msme_number||''} onChange={e=>set('msme_number',e.target.value)}/></Field></div></Section>
      <Section icon={BriefcaseBusiness} title="Services"><div className="flex flex-wrap gap-2">{SERVICES.map(s=><button key={s} type="button" onClick={()=>toggleService(s)} className={`px-3 py-2 border text-xs font-semibold rounded-none ${form.services?.includes(s)?'bg-[#0D3B66] text-white border-[#0D3B66]':'bg-white text-slate-600 border-slate-300 hover:border-[#1F6FB2]'}`}>{s}</button>)}</div></Section>
      <Section icon={Shield} title="DSC Details"><div className="flex justify-end -mt-2"><Button type="button" size="sm" variant="outline" className="rounded-none h-9" onClick={addDSC}><Plus className="h-3.5 w-3.5 mr-1"/>Add DSC</Button></div>{(form.dsc_details||[]).length===0?<div className="text-xs text-slate-400">No DSC records added.</div>:(form.dsc_details||[]).map((d,i)=><div key={i} className="grid grid-cols-1 md:grid-cols-5 gap-3 border border-slate-100 p-3"><Field label="Certificate No."><Input className={input} value={d.certificate_number||''} onChange={e=>updateDSC(i,'certificate_number',e.target.value)}/></Field><Field label="Holder Name"><Input className={input} value={d.holder_name||''} onChange={e=>updateDSC(i,'holder_name',e.target.value)}/></Field><Field label="Issue Date"><Input type="date" className={input} value={d.issue_date||''} onChange={e=>updateDSC(i,'issue_date',e.target.value)}/></Field><Field label="Expiry Date"><Input type="date" className={input} value={d.expiry_date||''} onChange={e=>updateDSC(i,'expiry_date',e.target.value)}/></Field><div className="flex items-end"><Button type="button" variant="ghost" className="h-10 rounded-none text-red-600 w-full" onClick={()=>removeDSC(i)}><Trash2 className="h-3.5 w-3.5 mr-1"/>Remove</Button></div><div className="md:col-span-5"><Field label="Notes"><Input className={input} value={d.notes||''} onChange={e=>updateDSC(i,'notes',e.target.value)}/></Field></div></div>)}</Section>
      <Section icon={UserCheck} title="Task / Service Assignments"><div className="flex justify-end -mt-2"><Button type="button" size="sm" variant="outline" className="rounded-none h-9" onClick={addAssignment}><Plus className="h-3.5 w-3.5 mr-1"/>Add Assignment</Button></div>{(form.assignments||[]).length===0?<div className="text-xs text-slate-400">No user assignment added.</div>:(form.assignments||[]).map((a,i)=><div key={i} className="border border-slate-100 p-3 space-y-3"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Field label="User"><Select value={a.user_id||'__none__'} onValueChange={v=>updateAssignment(i,'user_id',v==='__none__'?'':v)}><SelectTrigger className={input}><SelectValue placeholder="Select user"/></SelectTrigger><SelectContent><SelectItem value="__none__">Unassigned</SelectItem>{users.map(u=><SelectItem key={u.id} value={u.id}>{u.full_name||u.email}</SelectItem>)}</SelectContent></Select></Field><div className="md:col-span-2 flex items-end"><Button type="button" variant="ghost" className="h-10 rounded-none text-red-600" onClick={()=>removeAssignment(i)}><Trash2 className="h-3.5 w-3.5 mr-1"/>Remove assignment</Button></div></div><div className="flex flex-wrap gap-2">{SERVICES.map(s=><button key={s} type="button" onClick={()=>toggleAssignmentService(i,s)} className={`px-2 py-1 border text-[10px] font-semibold rounded-none ${a.services?.includes(s)?'bg-blue-50 text-[#1F6FB2] border-[#1F6FB2]':'text-slate-500 border-slate-200'}`}>{s}</button>)}</div></div>)}</Section>
      <Section icon={FileText} title="Tally / Notes / Status"><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Tally Ledger Name"><Input className={input} value={form.tally_ledger_name||''} onChange={e=>set('tally_ledger_name',e.target.value)}/></Field><Field label="Tally Group"><Input className={input} value={form.tally_group||''} onChange={e=>set('tally_group',e.target.value)}/></Field><Field label="Status"><Select value={form.status||'active'} onValueChange={v=>set('status',v)}><SelectTrigger className={input}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">Active</SelectItem><SelectItem value="inactive">Inactive</SelectItem></SelectContent></Select></Field></div><Field label="Notes"><Textarea className="rounded-none min-h-[90px]" value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></Field></Section>
      <div className="flex justify-end gap-2 border-t border-slate-200 pt-4"><Button variant="outline" className="rounded-none" onClick={close} disabled={saving||docBusy}>Cancel</Button><Button className="rounded-none bg-[#0D3B66]" onClick={save} disabled={saving||docBusy}>{saving?<Loader2 className="h-4 w-4 mr-2 animate-spin"/>:<FileCheck className="h-4 w-4 mr-2"/>}{editing?'Save Changes':'Create Client'}</Button></div>
    </div>
  </div></div>}
 </section>;
}
