import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Plus, Pencil, Search, Loader2, Users2, Building2, Mail, Phone, MapPin, FileCheck, Shield, Trash2, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import api from '@/lib/api';
import { toast } from 'sonner';

const TYPES=[['proprietor','Proprietor'],['pvt_ltd','Private Limited'],['llp','LLP'],['public_ltd','Public Limited'],['section_8','Section 8 Company'],['partnership','Partnership'],['huf','HUF'],['trust','Trust'],['other','Other']];
const SERVICES=['GST','Trademark','Income Tax','ROC','Audit','Compliance','Company Registration','Tax Planning','Accounting','Payroll','Other'];
const EMPTY={company_name:'',client_type:'proprietor',client_type_other:'',contact_persons:[{name:'',email:'',phone:'',designation:'',birthday:'',din:''}],email:'',phone:'',birthday:'',address:'',city:'',state:'',pincode:'',services:[],dsc_details:[],assignments:[],notes:'',status:'active',referred_by:'',auditor:'',gstin:'',pan:'',gst_treatment:'regular',place_of_supply:'',default_payment_terms:'Due on receipt',credit_limit:'',opening_balance:'',opening_balance_type:'Dr',tally_ledger_name:'',tally_group:'Sundry Debtors',website:'',msme_number:'',gst_address:'',gst_city:'',gst_state:'',gst_pin:'',cin:'',llpin:'',proprietor_name:'',mca_fetch_date:''};
const Field=({label,children})=><div className="space-y-1.5"><Label className="text-[11px] font-semibold tracking-wide text-slate-600 uppercase">{label}</Label>{children}</div>;
const input='h-11 rounded-none';

export default function MasterDataClientManager(){
 const [clients,setClients]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState(EMPTY),[search,setSearch]=useState(''),[open,setOpen]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get('/clients');setClients(Array.isArray(r.data)?r.data:(r.data?.clients||[]));}catch(e){toast.error(e?.response?.data?.detail||'Failed to load clients')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const visible=useMemo(()=>{const q=search.trim().toLowerCase();return clients.filter(c=>!q||[c.company_name,c.email,c.phone,c.gstin,c.pan,c.city,c.state].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))},[clients,search]);
 const set=(k,v)=>setForm(p=>({...p,[k]:v}));
 const openNew=()=>{setEditing(null);setForm(JSON.parse(JSON.stringify(EMPTY)));setOpen(true)};
 const openEdit=c=>{setEditing(c);setForm({...EMPTY,...c,contact_persons:Array.isArray(c.contact_persons)&&c.contact_persons.length?c.contact_persons.map(x=>({...x,birthday:x.birthday?.slice?.(0,10)||x.birthday||''})):EMPTY.contact_persons,dsc_details:Array.isArray(c.dsc_details)?c.dsc_details:[],services:Array.isArray(c.services)?c.services:[]});setOpen(true)};
 const close=()=>{if(!saving){setOpen(false);setEditing(null)}};
 const save=async()=>{if(!form.company_name.trim())return toast.error('Client / company name is required');setSaving(true);try{const payload={...form,company_name:form.company_name.trim(),gstin:form.gstin?.trim().toUpperCase()||null,pan:form.pan?.trim().toUpperCase()||null,contact_persons:(form.contact_persons||[]).filter(x=>x.name?.trim()).map(x=>({...x,name:x.name.trim()})),services:form.services||[],dsc_details:form.dsc_details||[],assignments:form.assignments||[]};if(editing)await api.put(`/clients/${editing.id}`,payload);else await api.post('/clients',payload);toast.success(editing?'Client updated':'Client added to shared client master');close();await load()}catch(e){const d=e?.response?.data?.detail;toast.error(Array.isArray(d)?d.map(x=>x.msg).join(' | '):(d||'Could not save client'))}finally{setSaving(false)}};
 const toggleService=s=>set('services',(form.services||[]).includes(s)?form.services.filter(x=>x!==s):[...(form.services||[]),s]);
 const setContact=(i,k,v)=>set('contact_persons',(form.contact_persons||[]).map((c,n)=>n===i?{...c,[k]:v}:c));
 const addContact=()=>set('contact_persons',[...(form.contact_persons||[]),{name:'',email:'',phone:'',designation:'',birthday:'',din:''}]);
 const removeContact=i=>set('contact_persons',(form.contact_persons||[]).filter((_,n)=>n!==i));
 return <section id="clients" className="border border-slate-200 bg-white overflow-hidden">
  <div className="px-5 py-4 border-b border-slate-100 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="p-2 bg-blue-50"><Building2 className="h-5 w-5 text-[#1F6FB2]"/></div><div><div className="flex items-center gap-2"><h2 className="text-sm font-bold text-slate-800">Client Details &amp; Access</h2><span className="px-2 py-0.5 text-[10px] font-bold bg-blue-50 text-[#1F6FB2]">{clients.length}</span></div><p className="text-xs mt-1 text-slate-500">Shared client master. Records, Invoicing, Compliance, Proposals and every other module read the same client record.</p></div></div><Button onClick={openNew} className="h-9 rounded-none bg-[#0D3B66]"><Plus className="h-3.5 w-3.5 mr-1.5"/> Add Client</Button></div>
  <div className="px-5 py-3 bg-slate-50 border-b border-slate-100 flex items-center gap-3"><div className="relative flex-1"><Search className="h-4 w-4 absolute left-2.5 top-2.5 text-slate-400"/><Input className="pl-8 h-9 rounded-none bg-white" placeholder="Search client, GSTIN, PAN, phone, email…" value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="text-[11px] font-semibold text-slate-500">{visible.length} shown</span></div>
  {loading?<div className="py-12 flex justify-center"><Loader2 className="h-5 w-5 animate-spin text-slate-400"/></div>:visible.length===0?<div className="py-12 text-center text-sm text-slate-400">No clients found. Add a client here or create one from Records.</div>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-slate-50 border-b border-slate-200 text-left"><th className="px-4 py-3">Client</th><th className="px-4 py-3">Constitution</th><th className="px-4 py-3">GSTIN / PAN</th><th className="px-4 py-3">Contact</th><th className="px-4 py-3">Services</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody>{visible.map(c=><tr key={c.id} className="border-b border-slate-100 hover:bg-slate-50/70"><td className="px-4 py-3"><div className="font-semibold text-slate-800">{c.company_name||'—'}</div><div className="text-[11px] text-slate-400">{c.city||''}{c.state?` · ${c.state}`:''}</div></td><td className="px-4 py-3 text-xs text-slate-600">{TYPES.find(x=>x[0]===c.client_type)?.[1]||c.client_type||'—'}</td><td className="px-4 py-3 text-xs text-slate-600">{c.gstin||'—'}<div className="text-[11px] text-slate-400">{c.pan||'—'}</div></td><td className="px-4 py-3 text-xs text-slate-600">{c.email||'—'}<div>{c.phone||''}</div></td><td className="px-4 py-3 text-xs text-slate-600">{(c.services||[]).slice(0,3).join(', ')||'—'}{(c.services||[]).length>3?'…':''}</td><td className="px-4 py-3 text-right"><Button size="icon" variant="ghost" className="h-8 w-8 rounded-none" onClick={()=>openEdit(c)} title="Edit client"><Pencil className="h-3.5 w-3.5"/></Button></td></tr>)}</tbody></table></div>}
  <div className="px-5 py-3 border-t border-slate-100 bg-slate-50/70 text-[11px] text-slate-500 flex flex-wrap gap-5"><span>Shared client master for all modules</span><span>Records → Clients writes to this same collection</span><span>Master Data → Clients writes to this same collection</span></div>
  {open&&<div className="fixed inset-0 z-[100] bg-slate-900/50 flex items-center justify-center p-4"><div className="w-full max-w-5xl max-h-[92vh] overflow-y-auto bg-white border border-slate-200 shadow-2xl">
    <div className="sticky top-0 z-10 bg-[#0D3B66] text-white px-6 py-5 flex items-center justify-between"><div><div className="text-[10px] font-bold tracking-widest uppercase text-blue-200">Client Master</div><h3 className="text-xl font-bold">{editing?'Edit Client Profile':'New Client Profile'}</h3><p className="text-xs text-blue-100 mt-1">Same shared client record used by the Records tab.</p></div><Button variant="ghost" size="icon" className="h-9 w-9 rounded-none text-white hover:bg-white/10" onClick={close}><X className="h-5 w-5"/></Button></div>
    <div className="p-6 space-y-6">
      <div className="border border-slate-200 p-5"><div className="flex items-center gap-2 mb-4"><Building2 className="h-4 w-4 text-[#1F6FB2]"/><span className="font-bold text-sm uppercase tracking-wider text-slate-700">Client Information</span></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><Field label="Client / Company Name *"><Input className={input} value={form.company_name||''} onChange={e=>set('company_name',e.target.value)}/></Field><Field label="Constitution"><Select value={form.client_type||'proprietor'} onValueChange={v=>set('client_type',v)}><SelectTrigger className="rounded-none h-11"><SelectValue/></SelectTrigger><SelectContent>{TYPES.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></Field><Field label="Other Constitution"><Input className={input} value={form.client_type_other||''} onChange={e=>set('client_type_other',e.target.value)}/></Field><Field label="Email"><Input className={input} value={form.email||''} onChange={e=>set('email',e.target.value)}/></Field><Field label="Phone"><Input className={input} value={form.phone||''} onChange={e=>set('phone',e.target.value)}/></Field><Field label="Birthday"><Input className={input} type="date" value={form.birthday||''} onChange={e=>set('birthday',e.target.value)}/></Field><Field label="Website"><Input className={input} value={form.website||''} onChange={e=>set('website',e.target.value)}/></Field><Field label="Referred By"><Input className={input} value={form.referred_by||''} onChange={e=>set('referred_by',e.target.value)}/></Field><Field label="Auditor"><Input className={input} value={form.auditor||''} onChange={e=>set('auditor',e.target.value)}/></Field></div></div>
      <div className="border border-slate-200 p-5"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><Users2 className="h-4 w-4 text-[#1F6FB2]"/><span className="font-bold text-sm uppercase tracking-wider text-slate-700">Contact Persons</span></div><Button type="button" size="sm" variant="outline" className="rounded-none h-9" onClick={addContact}><Plus className="h-3.5 w-3.5 mr-1"/> Add Contact</Button></div>{(form.contact_persons||[]).map((c,i)=><div key={i} className="grid grid-cols-1 md:grid-cols-6 gap-3 border-b border-slate-100 pb-4 mb-4 last:border-0"><Field label="Name"><Input className={input} value={c.name||''} onChange={e=>setContact(i,'name',e.target.value)}/></Field><Field label="Email"><Input className={input} value={c.email||''} onChange={e=>setContact(i,'email',e.target.value)}/></Field><Field label="Phone"><Input className={input} value={c.phone||''} onChange={e=>setContact(i,'phone',e.target.value)}/></Field><Field label="Designation"><Input className={input} value={c.designation||''} onChange={e=>setContact(i,'designation',e.target.value)}/></Field><Field label="Birthday"><Input className={input} type="date" value={c.birthday||''} onChange={e=>setContact(i,'birthday',e.target.value)}/></Field><div className="flex items-end"><Button type="button" variant="ghost" className="h-11 w-full rounded-none text-red-600" disabled={(form.contact_persons||[]).length===1} onClick={()=>removeContact(i)}><Trash2 className="h-4 w-4 mr-1"/> Remove</Button></div></div>)}</div>
      <div className="border border-slate-200 p-5"><div className="flex items-center gap-2 mb-4"><MapPin className="h-4 w-4 text-[#1F6FB2]"/><span className="font-bold text-sm uppercase tracking-wider text-slate-700">Primary &amp; GST Address</span></div><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Field label="Address"><Textarea className="rounded-none min-h-[88px]" value={form.address||''} onChange={e=>set('address',e.target.value)}/></Field><Field label="City"><Input className={input} value={form.city||''} onChange={e=>set('city',e.target.value)}/></Field><Field label="State"><Input className={input} value={form.state||''} onChange={e=>set('state',e.target.value)}/></Field><Field label="PIN Code"><Input className={input} value={form.pincode||''} onChange={e=>set('pincode',e.target.value)}/></Field><Field label="GST Registered Address"><Textarea className="rounded-none min-h-[88px]" value={form.gst_address||''} onChange={e=>set('gst_address',e.target.value)}/></Field><Field label="GST City"><Input className={input} value={form.gst_city||''} onChange={e=>set('gst_city',e.target.value)}/></Field><Field label="GST State"><Input className={input} value={form.gst_state||''} onChange={e=>set('gst_state',e.target.value)}/></Field><Field label="GST PIN"><Input className={input} value={form.gst_pin||''} onChange={e=>set('gst_pin',e.target.value)}/></Field></div></div>
      <div className="border border-slate-200 p-5"><div className="flex items-center gap-2 mb-4"><FileCheck className="h-4 w-4 text-[#1F6FB2]"/><span className="font-bold text-sm uppercase tracking-wider text-slate-700">Tax &amp; Billing</span></div><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Field label="GSTIN"><Input className={input} value={form.gstin||''} onChange={e=>set('gstin',e.target.value.toUpperCase())}/></Field><Field label="PAN"><Input className={input} value={form.pan||''} onChange={e=>set('pan',e.target.value.toUpperCase())}/></Field><Field label="GST Treatment"><Select value={form.gst_treatment||'regular'} onValueChange={v=>set('gst_treatment',v)}><SelectTrigger className="rounded-none h-11"><SelectValue/></SelectTrigger><SelectContent>{['regular','composition','consumer','unregistered','unknown'].map(v=><SelectItem key={v} value={v}>{v.replace(/^./,x=>x.toUpperCase())}</SelectItem>)}</SelectContent></Select></Field><Field label="Place of Supply"><Input className={input} value={form.place_of_supply||''} onChange={e=>set('place_of_supply',e.target.value)}/></Field><Field label="Payment Terms"><Input className={input} value={form.default_payment_terms||''} onChange={e=>set('default_payment_terms',e.target.value)}/></Field><Field label="Credit Limit"><Input className={input} type="number" value={form.credit_limit??''} onChange={e=>set('credit_limit',e.target.value)}/></Field><Field label="Opening Balance"><Input className={input} type="number" value={form.opening_balance??''} onChange={e=>set('opening_balance',e.target.value)}/></Field><Field label="Balance Type"><Select value={form.opening_balance_type||'Dr'} onValueChange={v=>set('opening_balance_type',v)}><SelectTrigger className="rounded-none h-11"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Dr">Dr</SelectItem><SelectItem value="Cr">Cr</SelectItem></SelectContent></Select></Field><Field label="MSME Number"><Input className={input} value={form.msme_number||''} onChange={e=>set('msme_number',e.target.value)}/></Field></div></div>
      <div className="border border-slate-200 p-5"><div className="flex items-center gap-2 mb-4"><Shield className="h-4 w-4 text-[#1F6FB2]"/><span className="font-bold text-sm uppercase tracking-wider text-slate-700">Company / MCA Details &amp; Tally</span></div><div className="grid grid-cols-1 md:grid-cols-4 gap-4"><Field label="CIN"><Input className={input} value={form.cin||''} onChange={e=>set('cin',e.target.value.toUpperCase())}/></Field><Field label="LLPIN"><Input className={input} value={form.llpin||''} onChange={e=>set('llpin',e.target.value.toUpperCase())}/></Field><Field label="Proprietor Name"><Input className={input} value={form.proprietor_name||''} onChange={e=>set('proprietor_name',e.target.value)}/></Field><Field label="MCA Fetch Date"><Input className={input} type="date" value={form.mca_fetch_date||''} onChange={e=>set('mca_fetch_date',e.target.value)}/></Field><Field label="Tally Ledger Name"><Input className={input} value={form.tally_ledger_name||''} onChange={e=>set('tally_ledger_name',e.target.value)}/></Field><Field label="Tally Group"><Select value={form.tally_group||'Sundry Debtors'} onValueChange={v=>set('tally_group',v)}><SelectTrigger className="rounded-none h-11"><SelectValue/></SelectTrigger><SelectContent>{['Sundry Debtors','Sundry Creditors','Current Assets','Current Liabilities','Other'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field></div></div>
      <div className="border border-slate-200 p-5"><div className="font-bold text-sm uppercase tracking-wider text-slate-700 mb-3">Services</div><div className="flex flex-wrap gap-2">{SERVICES.map(s=><button type="button" key={s} onClick={()=>toggleService(s)} className={`h-9 px-3 border text-xs font-semibold rounded-none ${form.services?.includes(s)?'bg-[#0D3B66] text-white border-[#0D3B66]':'bg-white text-slate-600 border-slate-200'}`}>{s}</button>)}</div></div>
      <div className="border border-slate-200 p-5"><Field label="Notes"><Textarea className="rounded-none min-h-[110px]" value={form.notes||''} onChange={e=>set('notes',e.target.value)}/></Field></div>
    </div>
    <div className="sticky bottom-0 bg-white border-t border-slate-200 px-6 py-4 flex justify-end gap-2"><Button type="button" variant="ghost" className="h-10 rounded-none" onClick={close}>Cancel</Button><Button type="button" className="h-10 rounded-none bg-[#0D3B66]" disabled={saving} onClick={save}>{saving?<Loader2 className="h-4 w-4 mr-2 animate-spin"/>:null}{editing?'Update Client':'Create Client'}</Button></div>
  </div></div>}
 </section>;
}
