/**
 * Curated theme presets and templates for Website Studio.
 * Designed for complete non-technical users to quickly style or populate professional websites.
 */

export const THEME_PRESETS = [
  {
    id: "modern-blue",
    name: "Modern Blue",
    category: "Professional",
    description: "Clean, high-trust corporate palette with deep navy and vibrant cyan-blue accent.",
    primary: "#102A56",
    accent: "#2563EB",
    background: "#FFFFFF",
    text: "#0F172A",
    font: "Plus Jakarta Sans",
    radius: "16",
    width: "wide",
  },
  {
    id: "emerald-growth",
    name: "Emerald Growth",
    category: "Finance & Advisory",
    description: "Prosperity, security, and prestige for CA/CS, accounting, and advisory firms.",
    primary: "#064E3B",
    accent: "#10B981",
    background: "#FFFFFF",
    text: "#0F172A",
    font: "Plus Jakarta Sans",
    radius: "12",
    width: "wide",
  },
  {
    id: "slate-minimal",
    name: "Slate Minimal",
    category: "Modern",
    description: "Monochrome precision with sleek graphite borders and sharp contrast.",
    primary: "#0F172A",
    accent: "#0EA5E9",
    background: "#FFFFFF",
    text: "#1E293B",
    font: "Inter",
    radius: "8",
    width: "wide",
  },
  {
    id: "indigo-tech",
    name: "Indigo Startup",
    category: "Technology",
    description: "Energetic digital palette ideal for modern SaaS, platforms, and tech agencies.",
    primary: "#312E81",
    accent: "#6366F1",
    background: "#FFFFFF",
    text: "#111827",
    font: "Poppins",
    radius: "20",
    width: "wide",
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    category: "High-End",
    description: "Warm onyx, charcoal, and warm golden ochre for high-end boutique practices.",
    primary: "#1C1917",
    accent: "#D97706",
    background: "#FAFAF9",
    text: "#1C1917",
    font: "Montserrat",
    radius: "12",
    width: "compact",
  },
  {
    id: "crimson-bold",
    name: "Crimson Bold",
    category: "Dynamic",
    description: "Confident deep ruby tone with crimson energy for modern service brands.",
    primary: "#450A0A",
    accent: "#EF4444",
    background: "#FFFFFF",
    text: "#0F172A",
    font: "Plus Jakarta Sans",
    radius: "14",
    width: "wide",
  },
  {
    id: "fresh-teal",
    name: "Fresh Teal",
    category: "Creative",
    description: "Approachable marine teal and vibrant mint for modern consultants.",
    primary: "#134E4A",
    accent: "#14B8A6",
    background: "#F0FDFA",
    text: "#0F172A",
    font: "Open Sans",
    radius: "16",
    width: "wide",
  },
  {
    id: "royal-purple",
    name: "Royal Velvet",
    category: "Creative",
    description: "Distinguished deep violet with lavender accents for creative agencies.",
    primary: "#3B0764",
    accent: "#8B5CF6",
    background: "#FAF5FF",
    text: "#1E1B4B",
    font: "Poppins",
    radius: "18",
    width: "wide",
  },
];

export const SAFE_FONTS = [
  { name: "Plus Jakarta Sans", category: "Modern & Clean (Recommended)" },
  { name: "Inter", category: "Crisp & Neutral" },
  { name: "Poppins", category: "Friendly & Geometric" },
  { name: "Montserrat", category: "Bold & Editorial" },
  { name: "Roboto", category: "Technical & Legible" },
  { name: "Open Sans", category: "Open & Balanced" },
  { name: "Lato", category: "Warm & Corporate" },
];

export const STOCK_LIBRARY_MEDIA = [
  {
    id: "med_onenexa",
    title: "ONENEXA Emblem",
    category: "Logos",
    url: "/onenexa-logo.png",
  },
  {
    id: "med_tasko",
    title: "Taskosphere Transparent",
    category: "Logos",
    url: "/logo-transparent.png",
  },
  {
    id: "med_finix",
    title: "Finix Accounting Logo",
    category: "Logos",
    url: "/finix-logo.png",
  },
  {
    id: "med_compligenie",
    title: "CompliGenie Compliance Logo",
    category: "Logos",
    url: "/compligenie-logo.png",
  },
  {
    id: "med_people",
    title: "People Matrix HRMS Logo",
    category: "Logos",
    url: "/people-matrix-logo.png",
  },
  {
    id: "med_leadsense",
    title: "LeadSense CRM Logo",
    category: "Logos",
    url: "/leadsense-logo.png",
  },
  {
    id: "med_office_1",
    title: "Modern Executive Office",
    category: "Images",
    url: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "med_meeting_2",
    title: "Collaborative Team Session",
    category: "Images",
    url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "med_finance_3",
    title: "Financial Reports & Analytics",
    category: "Images",
    url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "med_desk_4",
    title: "Executive Workstation",
    category: "Images",
    url: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "med_handshake_5",
    title: "Professional Partnership",
    category: "Images",
    url: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80",
  },
  {
    id: "med_city_6",
    title: "Financial Business District",
    category: "Images",
    url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
  },
];

export const PAGE_TEMPLATES = [
  {
    id: "blank",
    name: "Blank Page",
    description: "Start completely clean with a simple headline section.",
    sections: [
      {
        id: "hero",
        type: "hero",
        title: "Welcome Hero",
        visible: true,
        layout: "split",
        data: {
          badge: "NEW PAGE",
          title: "Page Title Goes Here",
          subtitle: "Add your text, pictures, and buttons using the simple panels on the right.",
          primaryText: "Get In Touch",
          primaryHref: "#contact",
          image: "/onenexa-logo.png",
          theme: "light",
        },
      },
    ],
  },
  {
    id: "about",
    name: "About Us",
    description: "Introduce your story, purpose, leadership, and credentials.",
    sections: [
      {
        id: "hero",
        type: "hero",
        title: "About Our Firm",
        visible: true,
        layout: "split",
        data: {
          badge: "OUR STORY",
          title: "Dedicated to Client Success & High Standards",
          subtitle: "We combine deep domain expertise, disciplined execution, and modern digital tools to deliver measurable business results.",
          primaryText: "Contact Leadership",
          primaryHref: "#contact",
          image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
          theme: "executive",
        },
      },
      {
        id: "story",
        type: "imageText",
        title: "Our Mission",
        visible: true,
        data: {
          heading: "Built On Integrity, Precision & Trust",
          body: "Founded with the ambition to simplify complex commercial operations, our team partners with founders, executives, and organizations to navigate regulatory, accounting, and operational hurdles.\n\nEvery solution we deploy is tailored to the exact requirements of your business with absolute data security and personal care.",
          image: "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
          imageSide: "right",
        },
      },
      {
        id: "testimonials",
        type: "testimonials",
        title: "Leadership Values",
        visible: true,
        data: {
          heading: "What Partners Say",
          items: [
            { quote: "Their team brought clarity to our finances and reduced our compliance overhead by 80%.", name: "Rajesh Sharma", role: "Managing Director, Apex Technologies" },
            { quote: "Proactive communication, zero missed deadlines, and genuine strategic advice.", name: "Pooja Varma", role: "Chief Operating Officer, Varma Logistics" },
          ],
        },
      },
      {
        id: "cta",
        type: "cta",
        title: "Ready to Talk?",
        visible: true,
        data: {
          heading: "Schedule a Consultation with Our Partners",
          text: "Discuss your requirements in a private, confidential session.",
          button: "Schedule Consultation",
          href: "/login",
        },
      },
    ],
  },
  {
    id: "services",
    name: "Services",
    description: "Showcase service offerings, capabilities, and deliverables.",
    sections: [
      {
        id: "hero",
        type: "hero",
        title: "Services Overview",
        visible: true,
        layout: "split",
        data: {
          badge: "OUR SPECIALTIES",
          title: "Comprehensive Solutions for Enterprise Operations",
          subtitle: "From accounting and tax compliance to operational task governance, we support every phase of your journey.",
          primaryText: "Explore Packages",
          primaryHref: "#pricing",
          image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
          theme: "executive",
        },
      },
      {
        id: "features",
        type: "features",
        title: "Core Services",
        visible: true,
        layout: "cards",
        data: {
          heading: "Specialized Business Solutions",
          subtitle: "Structured processes backed by seasoned subject-matter professionals.",
          items: [
            { title: "Statutory & GST Compliance", description: "Filing, periodic audit checks, reconciliations, and regulatory notices handling.", route: "#contact" },
            { title: "Corporate Accounting & Advisory", description: "Books of accounts, management reports, monthly closing, and financial controls.", route: "#contact" },
            { title: "Payroll & HRMS Automation", description: "Salary slips, tax computation, leave, and attendance record management.", route: "#contact" },
            { title: "ROC & Company Law", description: "Incorporations, director KYC, annual returns, and secretarial records.", route: "#contact" },
            { title: "Client Records & DSC Vault", description: "Secure credential repository, token registry, and document approvals.", route: "#contact" },
            { title: "Process Automation", description: "Custom workflow automation and digital workspace deployment.", route: "#contact" },
          ],
        },
      },
      {
        id: "cta",
        type: "cta",
        title: "Get Service Estimate",
        visible: true,
        data: {
          heading: "Need a Custom Solution For Your Firm?",
          text: "Tell us about your team size and key requirements for a transparent proposal.",
          button: "Request Proposal",
          href: "/login",
        },
      },
    ],
  },
  {
    id: "pricing",
    name: "Pricing & Plans",
    description: "Clear package tiers, pricing comparisons, and feature lists.",
    sections: [
      {
        id: "hero",
        type: "hero",
        title: "Pricing Header",
        visible: true,
        layout: "center",
        data: {
          badge: "SIMPLE PACKAGING",
          title: "Transparent Plans for Every Business Scale",
          subtitle: "Predictable monthly or annual plans. No surprise fees, cancel or upgrade anytime.",
          primaryText: "Compare Packages",
          primaryHref: "#pricing-cards",
          theme: "light",
        },
      },
      {
        id: "pricing-cards",
        type: "pricing",
        title: "Pricing Packages",
        visible: true,
        data: {
          heading: "Choose Your Commercial Package",
          subtitle: "Every plan includes complete security, automated backups, and dedicated support.",
          items: [
            { name: "Starter", price: "₹4,999", period: "/ month", description: "Ideal for early-stage companies needing tasks and invoicing.", featured: false },
            { name: "Professional", price: "₹9,999", period: "/ month", description: "Complete package including HRMS, Compliance & Banking.", featured: true },
            { name: "Enterprise", price: "₹24,999", period: "/ month", description: "Dedicated cloud, unlimited users, and customized workflows.", featured: false },
          ],
        },
      },
      {
        id: "faq",
        type: "faq",
        title: "Pricing FAQ",
        visible: true,
        data: {
          heading: "Frequently Asked Questions",
          items: [
            { question: "Can we change our plan later?", answer: "Yes, you can upgrade, downgrade, or add modules at any time from your commercial console." },
            { question: "Is there any setup fee?", answer: "No setup fees. You get instant access upon license activation." },
            { question: "Is my business data secure?", answer: "All data is encrypted in transit and at rest with role-based permission safeguards." },
          ],
        },
      },
    ],
  },
  {
    id: "contact",
    name: "Contact & Enquiry",
    description: "Direct contact form, addresses, office phone, and WhatsApp link.",
    sections: [
      {
        id: "hero",
        type: "hero",
        title: "Contact Hero",
        visible: true,
        layout: "split",
        data: {
          badge: "REACH OUT",
          title: "Let's Start a Conversation",
          subtitle: "We typically respond within two business hours. Visit our offices or submit an enquiry below.",
          primaryText: "Send Message",
          primaryHref: "#enquiry-form",
          image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80",
          theme: "executive",
        },
      },
      {
        id: "enquiry-form",
        type: "form",
        title: "Contact Form",
        visible: true,
        data: {
          heading: "Send Us a Direct Message",
        },
      },
      {
        id: "faq",
        type: "faq",
        title: "Working With Us",
        visible: true,
        data: {
          heading: "What Happens Next?",
          items: [
            { question: "How quickly will an advisor contact me?", answer: "Our partner team reviews incoming requests and responds within 2-4 business hours." },
            { question: "Can we sign an NDA prior to discussion?", answer: "Yes, we are pleased to execute mutual confidentiality agreements prior to sharing proprietary data." },
          ],
        },
      },
    ],
  },
  {
    id: "faq",
    name: "FAQ",
    description: "Detailed accordion questions and answers for customer reassurance.",
    sections: [
      {
        id: "hero",
        type: "hero",
        title: "Help Center",
        visible: true,
        layout: "center",
        data: {
          badge: "KNOWLEDGE & ANSWERS",
          title: "Everything You Need to Know",
          subtitle: "Browse frequently asked questions regarding our services, onboarding, and agreements.",
          theme: "light",
        },
      },
      {
        id: "faq-list",
        type: "faq",
        title: "Detailed FAQ",
        visible: true,
        data: {
          heading: "Common Questions",
          items: [
            { question: "What documents are required to begin onboarding?", answer: "PAN, Certificate of Incorporation/Partnership deed, GST certificate, and authorized signatory details." },
            { question: "How are compliance deadlines tracked?", answer: "Our automated alert system monitors statutory cutoffs, sending proactive reminders before dues." },
            { question: "Do you provide dedicated account managers?", answer: "Yes, every client is assigned a designated senior partner and operational manager." },
            { question: "Can multi-branch firms use the platform?", answer: "Yes, the platform supports multi-branch, multi-entity, and consolidation setups." },
          ],
        },
      },
      {
        id: "cta",
        type: "cta",
        title: "Still Have Questions?",
        visible: true,
        data: {
          heading: "Still have questions? We are here to help.",
          text: "Connect with our advisory desk for individualized guidance.",
          button: "Contact Us",
          href: "/login",
        },
      },
    ],
  },
  {
    id: "gallery",
    name: "Gallery & Portfolio",
    description: "Grid showcase of photos, client offices, and milestone projects.",
    sections: [
      {
        id: "hero",
        type: "hero",
        title: "Gallery Hero",
        visible: true,
        layout: "center",
        data: {
          badge: "SHOWCASE",
          title: "Our Work, Spaces & Milestones",
          subtitle: "A glimpse inside our modern workspace, events, and client engagements.",
          theme: "light",
        },
      },
      {
        id: "gallery-grid",
        type: "gallery",
        title: "Photo Showcase",
        visible: true,
        data: {
          items: [
            "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80",
          ],
        },
      },
    ],
  },
];

export const FULL_SITE_TEMPLATES = [
  {
    id: "business-corp",
    name: "Business & Corporate Firm",
    industry: "Corporate & Enterprise",
    tagline: "High-trust professional design for corporate entities and consultancies.",
    theme: THEME_PRESETS[0],
    site_name: "Apex Business Solutions",
    site_tagline: "Intelligent Corporate Advisory & Operations",
    pages: [
      PAGE_TEMPLATES.find((p) => p.id === "about"),
      PAGE_TEMPLATES.find((p) => p.id === "services"),
      PAGE_TEMPLATES.find((p) => p.id === "pricing"),
      PAGE_TEMPLATES.find((p) => p.id === "contact"),
    ],
  },
  {
    id: "ca-cs-firm",
    name: "Chartered Accountants & CS Firm",
    industry: "Tax, Audit & Legal",
    tagline: "Prestige emerald styling built for CA, CS, and audit practitioners.",
    theme: THEME_PRESETS[1],
    site_name: "Vanguard CA & Associates",
    site_tagline: "Statutory Audit, Tax Advisory & Corporate Secretarial",
    pages: [
      PAGE_TEMPLATES.find((p) => p.id === "about"),
      PAGE_TEMPLATES.find((p) => p.id === "services"),
      PAGE_TEMPLATES.find((p) => p.id === "faq"),
      PAGE_TEMPLATES.find((p) => p.id === "contact"),
    ],
  },
  {
    id: "tech-saas",
    name: "SaaS & Modern Tech Startup",
    industry: "Software & Technology",
    tagline: "Vibrant indigo visuals with high-converting call to action sections.",
    theme: THEME_PRESETS[3],
    site_name: "CloudNexa Cloud Suite",
    site_tagline: "Next-Generation Connected Workspace Software",
    pages: [
      PAGE_TEMPLATES.find((p) => p.id === "services"),
      PAGE_TEMPLATES.find((p) => p.id === "pricing"),
      PAGE_TEMPLATES.find((p) => p.id === "faq"),
      PAGE_TEMPLATES.find((p) => p.id === "contact"),
    ],
  },
  {
    id: "law-practice",
    name: "Law Firm & Legal Counsel",
    industry: "Legal & Advisory",
    tagline: "Authoritative luxury styling for legal chambers and dispute practitioners.",
    theme: THEME_PRESETS[4],
    site_name: "Sovereign Legal Chambers",
    site_tagline: "Corporate Law, Dispute Resolution & Compliance",
    pages: [
      PAGE_TEMPLATES.find((p) => p.id === "about"),
      PAGE_TEMPLATES.find((p) => p.id === "services"),
      PAGE_TEMPLATES.find((p) => p.id === "contact"),
    ],
  },
  {
    id: "creative-agency",
    name: "Creative Studio & Digital Agency",
    industry: "Design & Marketing",
    tagline: "Showcase portfolio, high-impact imagery, and bold aesthetic typography.",
    theme: THEME_PRESETS[7],
    site_name: "Prism Creative Studio",
    site_tagline: "Brand Identity, Digital Design & Growth Strategy",
    pages: [
      PAGE_TEMPLATES.find((p) => p.id === "gallery"),
      PAGE_TEMPLATES.find((p) => p.id === "services"),
      PAGE_TEMPLATES.find((p) => p.id === "contact"),
    ],
  },
];
