import React from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Check, Play, Quote } from "lucide-react";

export const DEFAULT_BUILDER = {
  version: 6,
  activePageId: "home",
  pages: [{
    id: "home", name: "Home", slug: "/", visible: true,
    sections: [
      { id: "hero", type: "hero", title: "Hero", visible: true, layout: "split", data: {
        badge: "THE MODERN BUSINESS OPERATING SYSTEM",
        title: "Everything your business needs. Nothing scattered.",
        subtitle: "Task management, invoicing, accounting, HRMS, records, compliance and AI — connected in one intelligent workspace.",
        primaryText: "Explore Taskosphere", primaryHref: "#features", secondaryText: "Sign in", secondaryHref: "/login", image: "/logo-transparent.png", theme: "executive"
      }},
      { id: "features", type: "features", title: "Platform Modules", visible: true, layout: "cards", data: {
        heading: "One platform. Every business function.", subtitle: "Choose the exact software package your customer needs and activate it through your commercial license.",
        items: [
          { title: "Task Management", description: "Projects, tasks, workflows, reminders and team visibility.", route: "/tasks" },
          { title: "Invoicing & Billing", description: "Quotations, invoices, purchases and customer billing.", route: "/invoicing" },
          { title: "Accounting & Banking", description: "Ledgers, banking, financial reports and audit controls.", route: "/accounting-reports" },
          { title: "HRMS & People", description: "Attendance, leave, payroll, recruitment and staff activity.", route: "/people-matrix" },
          { title: "Compliance & GST", description: "GST reconciliation, ROC, trademark and legal dates.", route: "/compliance-dashboard" },
          { title: "Client Records", description: "Client records, DSC repository, documents and approvals.", route: "/records-dashboard" },
          { title: "AI & Automation", description: "Intelligent document processing and operational assistance.", route: "/ai-reader" }
        ]
      }},
      { id: "why", type: "text", title: "Why Taskosphere", visible: true, data: { heading: "Run work from one connected workspace", body: "Assign and track work, communicate with your team, manage documents, monitor productivity and keep financial and compliance operations connected — without scattering information across different systems." }},
      { id: "pricing", type: "pricing", title: "Pricing & Licenses", visible: true, data: { heading: "Transparent Commercial Licensing", subtitle: "Activate standalone modular packages or deploy the complete enterprise business suite.", items: [
        { name: "Starter Suite", price: "₹4,999", period: "/ month", description: "Tasks, billing and client records.", featured: false },
        { name: "Professional Suite", price: "₹9,999", period: "/ month", description: "Invoicing, accounting, HRMS and compliance.", featured: true },
        { name: "Enterprise Custom", price: "Custom", period: "/ year", description: "Dedicated cloud, integrations and tailored workflows.", featured: false }
      ]}},
      { id: "cta", type: "cta", title: "Call to Action", visible: true, data: { heading: "Ready to build your Taskosphere workspace?", text: "Configure the modules your business needs and get started today.", button: "Sign in to workspace", href: "/login" }}
    ]
  }],
  global: { header: { sticky: true, showLogin: true, logo: true }, footer: { show: true, text: "A configurable commercial business operating system." }, design: { primary: "#0D3B66", accent: "#1FAF5A", background: "#FFFFFF", text: "#0F172A", font: "Plus Jakarta Sans", radius: "medium", width: "wide" } },
  media: []
};

const cssUrl = (url) => url ? `url("${String(url).replace(/"/g, '\\"')}")` : "none";
const sectionStyle = (section, design) => { const s = section?.style || {}; return { backgroundColor: s.backgroundColor || "transparent", backgroundImage: s.backgroundImage ? cssUrl(s.backgroundImage) : "none", backgroundSize: s.backgroundSize || "cover", backgroundPosition: s.backgroundPosition || "center", color: s.textColor || design.text, textAlign: s.textAlign || "left", borderRadius: s.borderRadius ? `${s.borderRadius}px` : undefined, paddingTop: s.paddingTop != null ? `${s.paddingTop}px` : undefined, paddingBottom: s.paddingBottom != null ? `${s.paddingBottom}px` : undefined, minHeight: s.minHeight ? `${s.minHeight}px` : undefined }; };
const Container = ({ children, width = "wide", className = "" }) => <div className={`mx-auto w-full px-5 sm:px-8 ${width === "full" ? "max-w-none" : width === "compact" ? "max-w-4xl" : "max-w-7xl"} ${className}`}>{children}</div>;
function SmartLink({ href = "#", children, className = "", style }) { return href.startsWith("/") ? <Link to={href} className={className} style={style}>{children}</Link> : <a href={href} className={className} style={style}>{children}</a>; }

function Header({ builder, identity }) {
  const d = builder.global?.design || {}, h = builder.global?.header || {};
  return <header className={`${h.sticky ? "sticky top-0" : ""} z-40 border-b border-slate-200/80 bg-white/95 backdrop-blur`}><Container width={d.width || "wide"} className="flex min-h-[72px] items-center gap-5">
    <div className="flex min-w-0 flex-1 items-center gap-3">{h.logo !== false && <img src={identity?.logo_url || builder.global?.identity?.logoUrl || "/logo.png"} alt={identity?.site_name || "Taskosphere"} className="h-10 w-auto max-w-[180px] object-contain" />}<div className="min-w-0"><div className="truncate text-lg font-extrabold tracking-tight text-slate-900">{identity?.site_name || builder.global?.identity?.siteName || "Taskosphere"}</div><div className="hidden truncate text-xs text-slate-500 sm:block">{identity?.site_tagline || builder.global?.identity?.tagline || "One platform for tasks, finance, compliance and people."}</div></div></div>
    <nav className="hidden items-center justify-center gap-7 md:flex">{(builder.pages || []).filter(p => p.visible !== false).slice(0, 5).map(p => <a key={p.id} href={`#page-${p.id}`} className="whitespace-nowrap text-sm font-semibold text-slate-600 hover:text-slate-950">{p.name}</a>)}{(builder.pages?.[0]?.sections || []).slice(0, 4).map(s => <a key={s.id} href={`#section-${s.id}`} className="whitespace-nowrap text-sm font-semibold text-slate-600 hover:text-slate-950">{s.title}</a>)}</nav>
    {h.showLogin !== false && <SmartLink href="/login" className="shrink-0 rounded-xl px-4 py-2.5 text-sm font-bold text-white shadow-sm" style={{ background: d.primary || "#0D3B66" }}>Sign in</SmartLink>}
  </Container></header>;
}

function Hero({ section, global }) { const d = section.data || {}, design = global.design || {}, dark = d.theme !== "light"; const bg = d.backgroundColor || (dark ? `linear-gradient(135deg, ${design.primary || "#0D3B66"} 0%, #102A43 58%, #061827 100%)` : "#f8fafc"); const align = d.contentAlign || "left"; return <section id={`section-${section.id}`} style={{ ...sectionStyle(section, design), background: bg, color: dark ? "#fff" : design.text }}><Container width={design.width || "wide"} className="grid min-h-[520px] items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-24"><div className={`${align === "center" ? "text-center" : "text-left"} min-w-0`}>{d.badge && <div className={`mb-6 inline-flex max-w-full items-center rounded-full border px-3.5 py-1.5 text-[11px] font-bold uppercase tracking-[.14em] ${dark ? "border-white/15 bg-white/10 text-white/90" : "border-slate-200 bg-white text-slate-600"}`}>{d.badge}</div>}<h1 className="break-words text-4xl font-black leading-[1.03] tracking-[-.045em] sm:text-5xl lg:text-6xl xl:text-7xl">{d.title || ""}</h1>{d.subtitle && <p className={`mt-6 max-w-2xl text-base leading-7 sm:text-lg ${dark ? "text-white/75" : "text-slate-600"} ${align === "center" ? "mx-auto" : ""}`}>{d.subtitle}</p>}<div className={`mt-8 flex flex-wrap gap-3 ${align === "center" ? "justify-center" : "justify-start"}`}>{d.primaryText && <SmartLink href={d.primaryHref || "#"} className="rounded-xl px-6 py-3.5 text-sm font-bold text-white shadow-lg" style={{ background: design.accent || "#1FAF5A" }}>{d.primaryText}<ArrowRight size={16} className="ml-2 inline" /></SmartLink>}{d.secondaryText && <SmartLink href={d.secondaryHref || "/login"} className={`rounded-xl border px-6 py-3.5 text-sm font-bold ${dark ? "border-white/20 bg-white/10 text-white" : "border-slate-300 bg-white text-slate-800"}`}>{d.secondaryText}</SmartLink>}</div></div><div className={`relative flex min-h-[300px] items-center justify-center ${d.imagePosition === "left" ? "order-first lg:order-first" : ""}`}><div className={`flex w-full min-h-[300px] items-center justify-center overflow-hidden rounded-3xl border p-5 shadow-2xl ${dark ? "border-white/10 bg-white/10" : "border-slate-200 bg-white"}`}>{d.image ? <img src={d.image} alt="" className="max-h-[340px] max-w-full object-contain" /> : <div className="text-sm opacity-60">Add a hero image</div>}</div></div></Container></section>; }
function Features({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-20"><Container width={design.width || "wide"}><div className="mx-auto mb-12 max-w-3xl text-center"><h2 className="text-3xl font-black tracking-tight sm:text-4xl">{d.heading}</h2>{d.subtitle && <p className="mt-4 text-base leading-7 text-slate-600">{d.subtitle}</p>}</div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{(d.items || []).map((item, i) => <SmartLink key={i} href={item.route || "#"} className="group rounded-2xl border border-slate-200 bg-white p-6 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl text-white" style={{ background: design.primary || "#0D3B66" }}><Check size={19} /></div><h3 className="text-lg font-extrabold text-slate-900">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{item.description}</p>{item.route && <span className="mt-5 inline-flex items-center text-xs font-bold" style={{ color: design.primary || "#0D3B66" }}>Explore <ArrowRight size={14} className="ml-1" /></span>}</SmartLink>)}</div></Container></section>; }
function TextSection({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-20"><Container width="compact"><h2 className="text-3xl font-black tracking-tight sm:text-4xl">{d.heading}</h2><p className="mt-5 whitespace-pre-wrap text-base leading-8 text-slate-600">{d.body}</p></Container></section>; }
function Pricing({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-20"><Container width={design.width || "wide"}><div className="mx-auto mb-12 max-w-3xl text-center"><h2 className="text-3xl font-black sm:text-4xl">{d.heading}</h2><p className="mt-4 text-slate-600">{d.subtitle}</p></div><div className="grid gap-6 lg:grid-cols-3">{(d.items || []).map((item, i) => <div key={i} className={`rounded-3xl border p-7 ${item.featured ? "border-2 shadow-xl" : "border-slate-200 shadow-sm"}`} style={item.featured ? { borderColor: design.accent || "#1FAF5A" } : undefined}><h3 className="text-lg font-extrabold">{item.name}</h3><div className="mt-5 text-4xl font-black">{item.price}</div><div className="mt-1 text-sm text-slate-500">{item.period}</div><p className="mt-5 text-sm leading-6 text-slate-600">{item.description}</p><SmartLink href="/login" className="mt-7 block rounded-xl px-4 py-3 text-center text-sm font-bold text-white" style={{ background: design.primary || "#0D3B66" }}>Get started</SmartLink></div>)}</div></Container></section>; }
function Cta({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={{ ...sectionStyle(section, design), background: d.backgroundColor || design.primary || "#0D3B66", color: "#fff" }} className="py-16"><Container width="compact" className="text-center"><h2 className="text-3xl font-black sm:text-4xl">{d.heading}</h2><p className="mx-auto mt-4 max-w-2xl text-white/75">{d.text}</p><SmartLink href={d.href || "/login"} className="mt-7 inline-flex items-center rounded-xl bg-white px-6 py-3.5 text-sm font-bold" style={{ color: design.primary || "#0D3B66" }}>{d.button || "Get started"}<ArrowRight size={16} className="ml-2" /></SmartLink></Container></section>; }
function ImageText({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-20"><Container width={design.width || "wide"}><div className="grid items-center gap-10 lg:grid-cols-2"><div className={d.imageSide === "left" ? "lg:order-first" : "lg:order-last"}>{d.image && <img src={d.image} alt="" className="w-full rounded-3xl border border-slate-200 object-cover shadow-lg" />}</div><div><h2 className="text-3xl font-black">{d.heading}</h2><p className="mt-5 whitespace-pre-wrap text-base leading-8 text-slate-600">{d.body}</p></div></div></Container></section>; }
function ImageSection({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-12"><Container width={design.width || "wide"}><img src={d.image} alt={d.alt || ""} className="max-h-[720px] w-full rounded-3xl object-cover shadow-lg" /></Container></section>; }
function Gallery({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-16"><Container width={design.width || "wide"}><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(d.items || []).map((src, i) => <img key={i} src={typeof src === "string" ? src : src.url} alt="" className="aspect-[4/3] w-full rounded-2xl object-cover" />)}</div></Container></section>; }
function VideoSection({ section, global }) { const d = section.data || {}, design = global.design || {}, url = d.url || d.video || ""; const embed = url.includes("youtube.com/watch?v=") ? `https://www.youtube.com/embed/${url.split("v=")[1].split("&")[0]}` : url; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-16"><Container width="wide"><div className="aspect-video overflow-hidden rounded-3xl bg-slate-950 shadow-xl">{embed ? <iframe title={d.title || "Video"} src={embed} className="h-full w-full" allowFullScreen /> : <div className="flex h-full items-center justify-center text-white"><Play /></div>}</div></Container></section>; }
function Testimonials({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-20"><Container width="wide"><h2 className="mb-10 text-center text-3xl font-black">{d.heading || "What customers say"}</h2><div className="grid gap-5 md:grid-cols-2">{(d.items || []).map((x, i) => <div key={i} className="rounded-2xl border border-slate-200 bg-white p-7"><Quote size={22} style={{ color: design.accent }} /><p className="mt-4 text-lg leading-7 text-slate-700">“{x.quote}”</p><div className="mt-5 text-sm font-bold">{x.name}</div><div className="text-xs text-slate-500">{x.role}</div></div>)}</div></Container></section>; }
function Faq({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-20"><Container width="compact"><h2 className="text-3xl font-black">{d.heading || "Frequently asked questions"}</h2><div className="mt-8 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white">{(d.items || []).map((x, i) => <details key={i} className="p-5"><summary className="cursor-pointer list-none font-bold">{x.question}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{x.answer}</p></details>)}</div></Container></section>; }
function FormSection({ section, global }) { const d = section.data || {}, design = global.design || {}; return <section id={`section-${section.id}`} style={sectionStyle(section, design)} className="py-20"><Container width="compact"><div className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><h2 className="text-3xl font-black">{d.heading || "Contact us"}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><input className="rounded-xl border border-slate-200 px-4 py-3" placeholder="Name" /><input className="rounded-xl border border-slate-200 px-4 py-3" placeholder="Email" /><textarea className="min-h-32 rounded-xl border border-slate-200 px-4 py-3 sm:col-span-2" placeholder="Message" /><button type="button" className="rounded-xl px-5 py-3 text-sm font-bold text-white sm:col-span-2" style={{ background: design.primary }}>Send enquiry</button></div></div></Container></section>; }

export function RenderSection({ section, global }) { if (section.visible === false) return null; const props = { section, global }; switch (section.type) { case "hero": return <Hero {...props} />; case "features": return <Features {...props} />; case "text": return <TextSection {...props} />; case "pricing": return <Pricing {...props} />; case "cta": return <Cta {...props} />; case "imageText": return <ImageText {...props} />; case "image": return <ImageSection {...props} />; case "gallery": return <Gallery {...props} />; case "video": return <VideoSection {...props} />; case "testimonials": return <Testimonials {...props} />; case "faq": return <Faq {...props} />; case "form": return <FormSection {...props} />; case "divider": return <div id={`section-${section.id}`} className="mx-auto my-8 h-px max-w-6xl bg-slate-200" />; default: return null; } }

export default function WebsiteRenderer({ builder, identity = {}, editor = false, selectedSectionId = null, onSelectSection }) {
  const source = builder && Array.isArray(builder.pages) ? builder : DEFAULT_BUILDER;
  const global = source.global || DEFAULT_BUILDER.global;
  const page = source.pages.find(p => p.id === source.activePageId) || source.pages[0];
  if (!page) return null;
  return <div className="min-h-full bg-white" style={{ color: global.design?.text || "#0F172A", fontFamily: global.design?.font || "Plus Jakarta Sans" }} onClick={() => editor && onSelectSection?.(null)}>
    <Header builder={source} identity={identity} />
    <main>{(page.sections || []).map(section => <div key={section.id} className={editor ? `relative cursor-pointer outline-offset-[-2px] transition ${selectedSectionId === section.id ? "outline-2 outline-blue-500" : "hover:outline hover:outline-1 hover:outline-blue-300"}` : ""} onClick={editor ? e => { e.stopPropagation(); onSelectSection?.(section.id); } : undefined}>{editor && selectedSectionId === section.id && <div className="pointer-events-none absolute left-3 top-3 z-30 rounded-full bg-blue-600 px-2 py-1 text-[10px] font-bold uppercase tracking-wider text-white">{section.title || section.type}</div>}<RenderSection section={section} global={global} /></div>)}</main>
    {global.footer?.show !== false && <footer className="border-t border-slate-200 bg-white py-10"><Container width={global.design?.width || "wide"} className="flex flex-col gap-4 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><div>{identity.footer_company || global.footer?.company || identity.site_name || "Taskosphere"} — {identity.footer_text || global.footer?.text || ""}</div><div>{identity.footer_copyright || global.footer?.copyright || "© 2026 Taskosphere. All rights reserved."}</div></Container></footer>}
  </div>;
}
