// Admin → Master Data: canonical company, client, user and reference-data hub.
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Plus, Trash2, Pencil, Loader2, Database, Building2, Download, Upload, Copy, Archive, RotateCcw, Check, X, ListTree, Tag, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import api from '@/lib/api';
import { toast } from 'sonner';
import useDark from '@/hooks/useDark';
import { useAuth } from '@/contexts/AuthContext.jsx';
import { ActionGuard } from '@/components/governance/GovernanceGuards';
import { CompanyProfilesList } from '@/components/CompanyProfiles';
import CompanyUserManager from '@/components/CompanyUserManager';
import PlatformUserManager from '@/components/PlatformUserManager';
import MasterDataClientManager from '@/components/MasterDataClientManager';
import { PageShell, PageBanner, StatRow, SectionCard, EmptyState, LoadingState, Toolbar, HUB_COLORS } from '@/components/ui/PageKit';
import '../../master-data-commercial.css';

const MODULE='admin';
const VIEW_FLAG='can_view_master_data';
const API_PATH='/master-data';
const DEFAULT_CATEGORIES=['Department','Task Category','Client Category','Document Type','Expense Head','Service','Bank','Other'];
const PLATFORM_OWNER_EMAIL='info.taskosphere@gmail.com';

export default function MasterData(){
 const { user } = useAuth();
 const platformOwner=String(user?.email||'').trim().toLowerCase()===PLATFORM_OWNER_EMAIL;
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[companyCount,setCompanyCount]=useState(null),[companies,setCompanies]=useState([]);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get(API_PATH);setItems(Array.isArray(r.data)?r.data:[])}catch{}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{api.get('/companies').then(r=>{const list=Array.isArray(r.data)?r.data:[];setCompanyCount(list.length);if(platformOwner)setCompanies(list)}).catch(()=>setCompanyCount(null))},[platformOwner]);
 const active=items.filter(i=>(i.status||'open')!=='archived').length;
 const categories=useMemo(()=>{const s=new Set(DEFAULT_CATEGORIES);items.forEach(i=>i.extra?.category&&s.add(i.extra.category));return [...s].sort()},[items]);
 return <PageShell className="master-data-page-shell">
   <PageBanner icon={Database} eyebrow="Admin" title="Master Data" subtitle="One place for company profiles, clients, users and the shared reference lists every other module reads from."/>
   <StatRow items={[{icon:Building2,label:'Company profiles',value:companyCount??'—',color:HUB_COLORS.mediumBlue},{icon:ListTree,label:'Reference entries',value:items.length,color:'#7C3AED'},{icon:Check,label:'Active',value:active,color:HUB_COLORS.emeraldGreen},{icon:Archive,label:'Archived',value:items.length-active,color:'#F59E0B'}]}/>
   <SectionCard icon={Building2} title="Company Profiles" badge={companyCount??undefined} description="The shared company master. Company records created or edited here remain the same company records used by Quotations, Invoicing, Trademark Sphere, WhatsApp/Email settings and GST Portal Sync."><CompanyProfilesList/></SectionCard>
   <MasterDataClientManager/>
   {platformOwner ? <div id="users"><PlatformUserManager companies={companies}/></div> : <div id="users"><CompanyUserManager/></div>}
   <ReferenceData items={items} loading={loading} reload={load} categories={categories}/>
 </PageShell>;
}

function ReferenceData({items,loading,reload,categories}){
 const isDark=useDark();
 const [search,setSearch]=useState(''),[category,setCategory]=useState('all'),[status,setStatus]=useState('active'),[sort,setSort]=useState('newest'),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[editingId,setEditingId]=useState(null),[draft,setDraft]=useState({title:'',code:'',category:'',details:''});
 const reset=()=>setDraft({title:'',code:'',category:'',details:''});
 const visible=useMemo(()=>{let list=[...items];if(status!=='all')list=list.filter(i=>status==='archived'?i.status==='archived':(i.status||'open')!=='archived');if(category!=='all')list=list.filter(i=>(i.extra?.category||'Other')===category);const q=search.trim().toLowerCase();if(q)list=list.filter(i=>`${i.title||''} ${i.details||''} ${i.extra?.code||''} ${i.extra?.category||''}`.toLowerCase().includes(q));list.sort((a,b)=>sort==='az'?(a.title||'').localeCompare(b.title||''):sort==='category'?(a.extra?.category||'').localeCompare(b.extra?.category||'')||(a.title||'').localeCompare(b.title||''):(b.created_at||'').localeCompare(a.created_at||''));return list},[items,search,category,status,sort]);
 const save=async()=>{if(!draft.title.trim())return;setBusy(true);try{const p={title:draft.title.trim(),details:draft.details.trim()||null,extra:{category:draft.category||'Other',code:draft.code.trim()||null}};if(editingId)await api.put(`${API_PATH}/${editingId}`,p);else await api.post(API_PATH,p);toast.success(editingId?'Updated':'Added');setEditingId(null);setAdding(false);reset();reload()}catch(e){toast.error(e?.response?.data?.detail||'Could not save')}finally{setBusy(false)}};
 const duplicate=async i=>{try{await api.post(API_PATH,{title:`${i.title} (copy)`,details:i.details||null,extra:i.extra||{}});toast.success('Duplicated');reload()}catch(e){toast.error(e?.response?.data?.detail||'Could not duplicate')}};
 const archive=async i=>{try{await api.put(`${API_PATH}/${i.id}`,{status:i.status==='archived'?'open':'archived'});toast.success(i.status==='archived'?'Restored':'Archived');reload()}catch(e){toast.error(e?.response?.data?.detail||'Could not update')}};
 const remove=async i=>{if(!window.confirm(`Delete “${i.title}” permanently?`))return;try{await api.delete(`${API_PATH}/${i.id}`);toast.success('Deleted');reload()}catch(e){toast.error(e?.response?.data?.detail||'Could not delete')}};
 const exportCsv=()=>{const rows=[['Category','Code','Title','Details','Status','Created by'],...visible.map(i=>[i.extra?.category||'',i.extra?.code||'',i.title||'',i.details||'',i.status||'',i.created_by_name||''])];const csv=rows.map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));a.download=`master-data-${new Date().toISOString().slice(0,10)}.csv`;a.click()};
 const importCsv=async file=>{if(!file)return;setBusy(true);try{const lines=(await file.text()).split(/\r?\n/).filter(Boolean).slice(1);let ok=0;for(const line of lines){const cells=line.match(/("([^\"]|"")*"|[^,]*)/g)?.filter((_,i)=>i%2===0)||[];const clean=cells.map(c=>c.replace(/^"|"$/g,'').replace(/""/g,'"').trim());const[cat,code,title,details]=clean;if(title){await api.post(API_PATH,{title,details:details||null,extra:{category:cat||'Other',code:code||null}});ok++}}toast.success(`Imported ${ok} row${ok===1?'':'s'}`);reload()}catch{toast.error('Could not import that CSV')}finally{setBusy(false)}};
 return <SectionCard icon={ListTree} color="#7C3AED" title="Reference Data" badge={visible.length} description="Departments, task/client categories, document types, expense heads and any other shared lookup list." actions={<><Button size="sm" variant="outline" onClick={exportCsv} disabled={!visible.length}><Download className="w-3.5 h-3.5 mr-1"/>Export</Button><ActionGuard module={MODULE} page={VIEW_FLAG} action="create"><label className="inline-flex"><input type="file" accept=".csv" className="hidden" onChange={e=>{importCsv(e.target.files?.[0]);e.target.value=''}}/><Button size="sm" variant="outline" asChild><span><Upload className="w-3.5 h-3.5 mr-1"/>Import CSV</span></Button></label></ActionGuard><ActionGuard module={MODULE} page={VIEW_FLAG} action="create"><Button size="sm" onClick={()=>{setEditingId(null);reset();setAdding(a=>!a)}}><Plus className="w-3.5 h-3.5 mr-1"/>Add entry</Button></ActionGuard></>}>
   {adding&&<div className={`p-4 mb-4 space-y-3 border ${isDark?'bg-slate-900/40 border-slate-700':'bg-slate-50 border-slate-200'}`}><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><select className="h-10 border px-3 text-sm bg-white" value={draft.category} onChange={e=>setDraft(d=>({...d,category:e.target.value}))}><option value="">Category…</option>{categories.map(c=><option key={c}>{c}</option>)}</select><Input placeholder="Code (optional)" value={draft.code} onChange={e=>setDraft(d=>({...d,code:e.target.value}))}/><Input placeholder="Title *" value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/></div><Input placeholder="Details / description" value={draft.details} onChange={e=>setDraft(d=>({...d,details:e.target.value}))}/><div className="flex gap-2"><Button onClick={save} disabled={busy||!draft.title.trim()}>{busy?<Loader2 className="w-4 h-4 mr-2 animate-spin"/>:<Check className="w-4 h-4 mr-2"/>}{editingId?'Save changes':'Add entry'}</Button><Button variant="ghost" onClick={()=>{setAdding(false);setEditingId(null);reset()}}><X className="w-4 h-4 mr-1"/>Cancel</Button></div></div>}
   <Toolbar className="mb-4"><div className="relative flex-1 min-w-[200px]"><Search className="w-4 h-4 absolute left-2.5 top-2.5 text-slate-400"/><Input className="pl-8" placeholder="Search title, code or details…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="h-10 border px-3 text-sm bg-white" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select><select className="h-10 border px-3 text-sm bg-white" value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="archived">Archived</option><option value="all">All</option></select><select className="h-10 border px-3 text-sm bg-white" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest first</option><option value="az">A → Z</option><option value="category">By category</option></select></Toolbar>
   {loading?<LoadingState/>:visible.length===0?<EmptyState icon={Database} title="No reference data yet" hint="Add departments, task categories, document types or any other list your team picks from."/>:<div className="space-y-2">{visible.map(i=><div key={i.id} className={`px-4 py-3 flex items-start justify-between gap-4 border ${isDark?'bg-slate-900/40 border-slate-700':'bg-slate-50 border-slate-100'} ${i.status==='archived'?'opacity-60':''}`}><div className="min-w-0"><div className="flex items-center gap-2 flex-wrap">{i.extra?.category&&<span className="text-[10px] font-extrabold px-2 py-0.5 bg-[#7C3AED]/15 text-[#7C3AED] inline-flex items-center gap-1"><Tag className="w-3 h-3"/>{i.extra.category}</span>}<span className="text-sm font-semibold">{i.title}</span>{i.extra?.code&&<span className="text-[10px] font-mono px-1.5 py-0.5 bg-slate-500/15 text-slate-400">{i.extra.code}</span>}{i.status==='archived'&&<span className="text-[10px] font-bold px-2 py-0.5 bg-amber-500/15 text-amber-600">Archived</span>}</div>{i.details&&<p className="text-xs mt-1 text-slate-500">{i.details}</p>}<p className="text-[11px] text-slate-400 mt-1">{i.created_by_name||'Unknown'}{i.created_at?` · ${new Date(i.created_at).toLocaleDateString()}`:''}</p></div><div className="flex gap-1 shrink-0"><Button variant="ghost" size="icon" title="Duplicate" className="rounded-none" onClick={()=>duplicate(i)}><Copy className="w-4 h-4"/></Button><Button variant="ghost" size="icon" title="Edit" className="rounded-none" onClick={()=>{setEditingId(i.id);setAdding(true);setDraft({title:i.title||'',code:i.extra?.code||'',category:i.extra?.category||'',details:i.details||''})}}><Pencil className="w-4 h-4"/></Button><Button variant="ghost" size="icon" title={i.status==='archived'?'Restore':'Archive'} className="rounded-none" onClick={()=>archive(i)}>{i.status==='archived'?<RotateCcw className="w-4 h-4"/>:<Archive className="w-4 h-4"/>}</Button><Button variant="ghost" size="icon" title="Delete" className="rounded-none" onClick={()=>remove(i)}><Trash2 className="w-4 h-4 text-red-500"/></Button></div></div>)}</div>}
 </SectionCard>;
}
