"""Canonical permission module hierarchy shared by governance and licensing."""

MODULE_HIERARCHY = {
    "taskosphere": {
        "flag": "can_access_taskosphere",
        "label": "Taskosphere",
        "description": "Core workspace — Tasks, To-Do, Attendance, Reminders, Action Center, Client Visits and Client Portal Manager.",
        "pages": [
            {"flag": "can_view_dashboard", "label": "Dashboard", "actions": ["view"]},
            {"flag": "can_view_tasks", "label": "Tasks", "actions": ["view", "create", "edit", "delete"]},
            {"flag": "can_view_todo_dashboard", "label": "To-Do", "actions": ["view", "create", "edit", "delete"]},
            {"flag": "can_view_attendance", "label": "Attendance", "actions": ["view", "edit"]},
            {"flag": "can_view_reminders", "label": "Reminders", "actions": ["view", "create", "edit", "delete"]},
            {"flag": "can_view_action_center", "label": "Action Center", "actions": ["view"]},
            {"flag": "can_view_client_visits", "label": "Client Visits", "actions": ["view", "create", "edit", "delete"]},
            {"flag": "can_view_client_portal", "label": "Client Portal Manager", "actions": ["view", "create", "edit", "delete", "export", "print", "share"]},
            {"flag": "can_reset_client_passwords", "label": "Password Reset", "actions": ["view", "edit", "export"]},
        ],
    },
    "finix": {
        "flag": "can_access_finix",
        "label": "Finix",
        "description": "Accounting & finance — Sales, Purchase, Bank Accounts, Chart of Accounts, Journal Entries and Accounting Reports.",
        "pages": [
            {"flag": "can_view_accounting_reports", "label": "Finix Dashboard & Accounting Reports", "actions": ["view", "export", "print"]},
            {"flag": "can_view_sale", "label": "Sales / Invoicing", "actions": ["view", "create", "edit", "delete", "export", "print", "share"]},
            {"flag": "can_view_purchase", "label": "Purchase", "actions": ["view", "create", "edit", "delete", "export", "print"]},
            {"flag": "can_view_bank", "label": "Bank Accounts", "actions": ["view", "create", "export"]},
            {"flag": "can_view_chart_of_accounts", "label": "Chart of Accounts (view)", "actions": ["view", "export"]},
            {"flag": "can_manage_chart_of_accounts", "label": "Chart of Accounts (manage)", "actions": ["create", "edit", "delete"]},
            {"flag": "can_view_journal_entries", "label": "Journal Entries (view)", "actions": ["view", "export"]},
            {"flag": "can_post_journal_entries", "label": "Journal Entries & Zero Touch Entry (post)", "actions": ["create", "edit", "approve"]},
            {"flag": "can_match_bank", "label": "Bank Reconciliation (match/unmatch)", "actions": ["edit"]},
        ],
    },
    "aiweave": {
        "flag": "can_access_aiweave",
        "label": "AIWeave",
        "description": "Unified AI workspace — document intelligence, AI analysis and shared AI workflows.",
        "pages": [{"flag": "can_view_aiweave", "label": "AIWeave Workspace", "actions": ["view", "create"]}],
    },
    "compliance": {
        "flag": "can_access_compliance",
        "label": "CompliGenie",
        "description": "Compliance Tracker, GST Reconciliation, Trademark Sphere, MIS Report, Salary Slip Generator and ROC Sphere.",
        "pages": [
            {"flag": "can_view_compliance", "label": "Compliance Tracker (view)", "actions": ["view", "export", "print"]},
            {"flag": "can_manage_compliance", "label": "Compliance Tracker (manage)", "actions": ["create", "edit", "delete", "approve"]},
            {"flag": "can_view_gst_reconciliation", "label": "GST Reconciliation", "actions": ["view", "export"]},
            {"flag": "can_view_trademark_sphere", "label": "Trademark Sphere", "actions": ["view", "create", "edit", "export", "print"]},
            {"flag": "can_view_mis_report", "label": "MIS Report (view)", "actions": ["view", "export", "print"]},
            {"flag": "can_manage_mis_report", "label": "MIS Report (manage)", "actions": ["create", "edit", "delete", "upload"]},
            {"flag": "can_view_salary_slips", "label": "Salary Slip Generator (view)", "actions": ["view", "export", "print"]},
            {"flag": "can_manage_salary_slips", "label": "Salary Slip Generator (manage)", "actions": ["create", "edit", "delete"]},
            {"flag": "can_view_roc_sphere", "label": "ROC Sphere (view)", "actions": ["view", "export", "print"]},
            {"flag": "can_manage_roc_sphere", "label": "ROC Sphere (manage)", "actions": ["create", "edit", "delete", "upload"]},
        ],
    },
    "records": {
        "flag": "can_access_records",
        "label": "Client Records",
        "description": "DSC Register, Document Register, Clients (with approval workflow) and Password Vault.",
        "pages": [
            {"flag": "can_view_all_dsc", "label": "DSC Register", "actions": ["view", "export"]},
            {"flag": "can_view_documents", "label": "Document Register", "actions": ["view", "export"]},
            {"flag": "can_view_passwords", "label": "Password Vault (view)", "actions": ["view"]},
            {"flag": "can_edit_passwords", "label": "Password Vault (manage)", "actions": ["create", "edit", "delete"]},
            {"flag": "can_view_all_clients", "label": "Clients — visibility of other users' clients", "actions": ["view"]},
            {"flag": "can_edit_clients", "label": "Clients — edit / update any client", "actions": ["edit", "update"]},
            {"flag": "can_approve_clients", "label": "Clients — approve newly added clients", "actions": ["approve"]},
            {"flag": "can_approve_whatsapp_wishes", "label": "Automation — approve WhatsApp birthday/festival wishes", "actions": ["approve"]},
            {"flag": "can_approve_email_wishes", "label": "Automation — approve Email birthday/festival wishes", "actions": ["approve"]},
        ],
    },
    "proposals": {
        "flag": "can_access_proposals",
        "label": "LeadSense",
        "description": "Lead management, quotations and client discussion threads.",
        "pages": [
            {"flag": "can_view_all_leads", "label": "Lead Management", "actions": ["view", "create", "edit", "delete", "export"]},
            {"flag": "can_create_quotations", "label": "Quotations", "actions": ["view", "create", "edit", "delete", "export", "print", "share", "approve"]},
            {"flag": "can_view_client_discussion", "label": "Client Discussion (view)", "actions": ["view"]},
            {"flag": "can_manage_client_discussion", "label": "Client Discussion (manage)", "actions": ["create", "edit", "delete"]},
        ],
    },
    "people_matrix": {
        "flag": "can_access_people_matrix",
        "label": "People Matrix",
        "description": "User directory, Attendance, Leave, Payroll, HR, Recruitment (candidate pipeline & interviews) and Performance (HRMS).",
        "pages": [
            {"flag": "can_view_user_page", "label": "User Directory", "actions": ["view", "export"]},
            {"flag": "can_view_leave", "label": "Leave (view)", "actions": ["view"]},
            {"flag": "can_manage_leave", "label": "Leave (manage)", "actions": ["create", "edit", "delete", "approve"]},
            {"flag": "can_view_payroll", "label": "Payroll (view)", "actions": ["view", "export"]},
            {"flag": "can_manage_payroll", "label": "Payroll (manage)", "actions": ["create", "edit", "approve"]},
            {"flag": "can_view_hr", "label": "HR (view)", "actions": ["view"]},
            {"flag": "can_manage_hr", "label": "HR (manage)", "actions": ["create", "edit", "delete"]},
            {"flag": "can_view_recruitment", "label": "Recruitment (view)", "actions": ["view", "export"]},
            {"flag": "can_manage_recruitment", "label": "Recruitment (manage)", "actions": ["create", "edit", "delete"]},
            {"flag": "can_view_performance", "label": "Performance (view)", "actions": ["view"]},
            {"flag": "can_manage_performance", "label": "Performance (manage)", "actions": ["create", "edit"]},
        ],
    },
    "admin": {
        "flag": "can_access_admin",
        "label": "Admin",
        "description": "Users, Permission Matrix, Audit Logs, Settings, Master Data, Roles and Activity Logs.",
        "pages": [
            {"flag": "can_view_user_page", "label": "Users", "actions": ["view", "create", "edit", "delete"]},
            {"flag": "can_manage_permissions", "label": "Permission Matrix", "actions": ["view", "edit", "approve"]},
            {"flag": "can_view_audit_logs", "label": "Audit Logs", "actions": ["view", "export"]},
            {"flag": "can_manage_settings", "label": "Settings", "actions": ["view", "edit"]},
            {"flag": "can_view_master_data", "label": "Master Data (view)", "actions": ["view"]},
            {"flag": "can_manage_master_data", "label": "Master Data (manage)", "actions": ["create", "edit", "delete"]},
            {"flag": "can_view_roles", "label": "Roles (view)", "actions": ["view"]},
            {"flag": "can_manage_roles", "label": "Roles (manage)", "actions": ["create", "edit", "delete"]},
            {"flag": "can_view_staff_activity", "label": "Activity Logs", "actions": ["view", "export"]},
        ],
    },
}
