import React,{useMemo,useState} from 'react';
import {Sparkles,Paperclip,Send,Receipt,ShoppingCart,WalletCards,Landmark,FileText,BarChart3,ArrowRight,ShieldCheck,Clock3} from 'lucide-react';
import api from '@/lib/api';
import RequestAccessGate from '@/components/RequestAccessGate.jsx';
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const quick=[['Sales invoice','Create a sales invoice'],['Purchase bill','Record a purchase bill'],['Payment','Record a payment'],['Receipt','Record money received'],['Bank transfer','Transfer between bank accounts'],['Expense','Record an expense']];
const reports=[['Day Book','/day-book',Receipt],['Ledger','/journal-entries',FileText],['Trial Balance','/accounting-reports',BarChart3],['P&L','/accounting-reports',BarChart3],['Balance Sheet','/accounting-reports',BarChart3],['Bank Reconciliation','/bank-reconciliation',Landmark]];
function Workspace(){
 const [text,setText]=useState(''); const [loading,setLoading]=useState(false); const [result,setResult]=useState(null); const [history,setHistory]=useState([]);
 const submit=async value=>{const prompt=(value??text).trim();if(!prompt)return;setLoading(true);setResult(null);try{const r=await api.post('/finix/ai/interpret',{text:prompt});setResult(r.data);setHistory(h=>[{text:prompt,result:r.data},...h].slice(0,8));setText('');}catch(e){setResult({error:e?.response?.data?.detail||'Finix AI could not process this yet.'});}finally{setLoading(false);}};
 const questions=result?.needs_clarification||[]; const ready=result?.success;
 return <div className="min-h-full bg-slate-50 text-slate-900 p-4 md:p-6"><div className="mx-auto max-w-7xl space-y-5">
  <div className="rounded-3xl bg-gradient-to-r from-slate-950 via-blue-950 to-cyan-900 p-6 md:p-8 text-white shadow-xl"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-cyan-300 font-semibold"><Sparkles size={18}/> FINIX AI ACCOUNTING</div><h1 className="mt-2 text-2xl md:text-4xl font-bold tracking-tight">Just tell Finix what happened.</h1><p className="mt-2 max-w-2xl text-slate-300">No debit-credit knowledge required. Describe a transaction in normal language and Finix prepares the accounting entry, GST treatment and reports.</p></div><div className="hidden md:flex rounded-2xl bg-white/10 p-3"><ShieldCheck/></div></div>
   <div className="mt-6 rounded-2xl bg-white p-2 flex gap-2 shadow-lg"><button className="p-3 text-slate-500" title="Attach document"><Paperclip size={20}/></button><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&submit()} placeholder="e.g. Paid ₹25,000 office rent to ABC Properties" className="min-w-0 flex-1 bg-transparent px-2 text-slate-900 outline-none"/><button disabled={loading} onClick={()=>submit()} className="rounded-xl bg-cyan-600 px-4 py-3 font-semibold flex items-center gap-2">{loading?'Thinking…':<><Send size={17}/> Ask Finix</>}</button></div>
  </div>
  <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3">{quick.map(([label,p])=><button key={label} onClick={()=>{setText(p);submit(p)}} className="rounded-2xl bg-white border border-slate-200 p-4 text-left hover:border-cyan-400 hover:shadow-sm transition"><div className="text-sm font-semibold">{label}</div><div className="text-xs text-slate-500 mt-1">AI-assisted</div></button>)}</div>
  {result&&<div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 rounded-3xl bg-white border border-slate-200 p-6 shadow-sm"><div className="flex justify-between gap-3"><div><div className="text-xs font-semibold text-cyan-700 uppercase">AI understanding</div><h2 className="text-xl font-bold mt-1">{result.error?'Needs attention':result.event||'Transaction review'}</h2></div>{result.confidence_band&&<span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{result.confidence_band} · {Math.round((result.confidence||0)*100)}%</span>}</div>{result.error?<p className="mt-5 text-red-600">{result.error}</p>:<><div className="mt-5 grid sm:grid-cols-3 gap-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Amount</div><div className="text-lg font-bold">{money(result.amount)}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Party</div><div className="text-lg font-bold truncate">{result.party_name||'To be selected'}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs text-slate-500">Policy</div><div className="text-lg font-bold">{result.policy?.status||'Review'}</div></div></div>{questions.length>0?<div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="font-semibold">I need a little more information</div>{questions.map((q,i)=><div key={i} className="mt-2 text-sm text-amber-900">{q}</div>)}</div>:<div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><div className="font-semibold text-emerald-800">Ready for governed posting</div><div className="text-sm text-emerald-700 mt-1">Finix will still validate the voucher, GST, duplicate and accounting controls before posting.</div></div>}</>}</div><div className="rounded-3xl bg-slate-950 text-white p-6"><div className="flex items-center gap-2 font-semibold"><Clock3 size={18}/> Recent AI activity</div>{history.length===0?<p className="mt-5 text-sm text-slate-400">Your AI accounting activity will appear here.</p>:history.map((h,i)=><div key={i} className="mt-4 border-b border-white/10 pb-3"><div className="text-sm">{h.text}</div><div className="text-xs text-slate-400 mt-1">{h.result?.event||'Review'}</div></div>)}</div></div>}
  <div className="rounded-3xl bg-white border border-slate-200 p-6"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Everything Finix handles for you</h2><p className="text-sm text-slate-500 mt-1">Traditional accounting screens remain available when you need control or detail.</p></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-5">{reports.map(([label,path,Icon])=><a key={label} href={path} className="rounded-2xl border border-slate-200 p-4 flex items-center gap-3 hover:border-cyan-400"><Icon size={20}/><span className="font-medium flex-1">{label}</span><ArrowRight size={16}/></a>)}</div></div>
 </div></div>;
}
export default function FinixAIWorkspace(){return <RequestAccessGate module="accounting_reports" moduleLabel="Finix AI Accounting" permissionFlag="can_view_accounting_reports"><Workspace/></RequestAccessGate>}
