import React, { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, Copy, Globe2, KeyRound, Package, Plus, Search, ShieldCheck, Users, XCircle, Building2, IndianRupee, CalendarDays, Mail, MapPin } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { generateCommercialLicense, getLicenseState, updateLicenseStatus } from "@/lib/licenseApi";

const MODULE_LABELS = { TASKS: "Task Management", INVOICING: "Invoicing", ACCOUNTING: "Accounting", HRMS: "HRMS" };
const initialForm = {
  company_name: "", contact_name: "", email: "", phone: "", gstin: "", address: "", gst_address: "", city: "", state: "", pincode: "",
  package_id: "essential", validity_months: 12, amount_charged: "", currency: "INR", max_users: 10, max_installations: 1, notes: "",
};
const formatDate = (value) => value ? new Date(value).toLocaleDateString("en-IN") : "Lifetime";
const money = (value) => Number(value || 0).toLocaleString("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 });

function Stat({ icon: Icon, label, value }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="rounded-xl bg-slate-100 p-2.5 w-fit"><Icon size={18} /></div><div className="mt-4 text-3xl font-bold text-slate-950">{value}</div><div className="mt-1 text-sm font-medium text-slate-600">{label}</div></div>; }

const Field = ({ label, children, className = "" }) => <label className={`text-sm font-medium text-slate-700 ${className}`}><span className="block">{label}</span>{children}</label>;
const Input = (props) => <input {...props} className={`mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-slate-400 ${props.className || ""}`} />;

export default function MasterConsole() {
  const navigate = useNavigate();
  const [state, setState] = useState({ packages: [], licenses: [], customers: [] });
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");
  const [showCreate, setShowCreate] = useState(false);
  const [form, setForm] = useState(initialForm);
  const [created, setCreated] = useState(null);

  const refresh = async () => {
    try { setState(await getLicenseState()); }
    catch (error) { toast.error(error?.response?.data?.detail || "Unable to connect to commercial licensing API."); }
    finally { setLoading(false); }
  };
  useEffect(() => { refresh(); }, []);

  const stats = useMemo(() => ({ total: state.licenses.length, active: state.licenses.filter((l) => l.status === "active" && (!l.expires_at || new Date(l.expires_at) >= new Date())).length, expired: state.licenses.filter((l) => l.expires_at && new Date(l.expires_at) < new Date()).length, customers: new Set(state.licenses.map((l) => l.customer_id)).size }), [state]);
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); if (!q) return state.licenses; return state.licenses.filter((l) => [l.license_key, l.customer_name, l.package_name, l.status, l.amount_charged, l.customer?.gstin].some((v) => String(v || "").toLowerCase().includes(q))); }, [query, state.licenses]);
  const packageChange = (id) => { const pkg = state.packages.find((p) => p.id === id); setForm((f) => ({ ...f, package_id: id, max_users: pkg?.max_users || f.max_users, max_installations: pkg?.max_installations || f.max_installations })); };
  const submit = async (event) => {
    event.preventDefault();
    try {
      const license = await generateCommercialLicense({ ...form, amount_charged: Number(form.amount_charged || 0), validity_months: Number(form.validity_months || 0), max_users: Number(form.max_users), max_installations: Number(form.max_installations) });
      setCreated(license.license || license); setShowCreate(false); setForm(initialForm); await refresh(); toast.success("License generated and customer record created.");
    } catch (error) { toast.error(error?.response?.data?.detail || "Unable to generate license."); }
  };
  const copy = async (key) => { await navigator.clipboard.writeText(key); toast.success("License number copied."); };
  const changeStatus = async (license, status) => { try { await updateLicenseStatus(license.id, status); await refresh(); toast.success(`License ${status}.`); } catch (error) { toast.error(error?.response?.data?.detail || "Unable to update license."); } };

  return <div className="min-h-screen bg-slate-50 p-4 md:p-7"><div className="mx-auto max-w-[1500px]">
    <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-400"><ShieldCheck size={15} /> Commercial Control Plane</div><h1 className="mt-1 text-3xl font-bold text-slate-950">Taskosphere Master Console</h1><p className="mt-1 text-sm text-slate-500">Licensing, customers and the complete customer-facing software website.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => navigate("/master-console/website")} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700 shadow-sm"><Globe2 size={17} /> Website & Branding</button><button onClick={() => setShowCreate(true)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17} /> Generate License</button></div></div>
    <div className="mt-7 rounded-2xl border border-slate-200 bg-white p-1.5 shadow-sm"><div className="flex flex-wrap items-center gap-1"><button className="rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Licensing Control</button><button onClick={() => navigate("/master-console/website")} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50"><span className="inline-flex items-center gap-2"><Globe2 size={15} /> Website Studio</span></button></div></div>
    <div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={KeyRound} label="Total Licenses" value={stats.total} /><Stat icon={CheckCircle2} label="Active Licenses" value={stats.active} /><Stat icon={XCircle} label="Expired Licenses" value={stats.expired} /><Stat icon={Users} label="Customers" value={stats.customers} /></div>
    <div className="mt-7 grid gap-5 lg:grid-cols-3"><section className="lg:col-span-2 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="font-bold text-slate-900">Commercial Packages</h2><p className="mt-1 text-sm text-slate-500">Entitlements are stored server-side.</p></div><Package size={20} className="text-slate-400" /></div><div className="mt-5 grid gap-4 md:grid-cols-3">{state.packages.map((pkg) => <div key={pkg.id} className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{pkg.code}</p><h3 className="mt-1 font-bold">{pkg.name}</h3><p className="mt-1 text-xs text-slate-500">{pkg.description}</p><div className="mt-3 flex flex-wrap gap-1.5">{pkg.modules.map((m) => <span key={m} className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-medium">{MODULE_LABELS[m] || m}</span>)}</div><p className="mt-3 text-xs text-slate-400">{pkg.max_users} users · {pkg.max_installations} installations</p></div>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="font-bold text-slate-900">Recent Activity</h2><div className="mt-5 space-y-4">{state.licenses.slice(0, 6).map((l) => <div key={l.id} className="flex items-center gap-3"><div className="rounded-lg bg-slate-100 p-2"><Activity size={15} /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{l.customer_name}</p><p className="text-xs text-slate-400">{l.package_name} · {l.validity_months || "—"} months</p></div><span className="text-xs text-slate-400">{formatDate(l.issued_at)}</span></div>)}{!state.licenses.length && <p className="text-sm text-slate-400">No licenses generated yet.</p>}</div></section></div>
    <section className="mt-5 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 md:flex-row md:items-center md:justify-between"><div><h2 className="font-bold">License Registry</h2><p className="mt-1 text-sm text-slate-500">Every license is read from the commercial backend.</p></div><div className="relative w-full md:w-80"><Search size={16} className="absolute left-3 top-3 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search customer, GSTIN, key or package" className="w-full rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-sm" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-400"><tr><th className="px-5 py-3">Customer</th><th className="px-5 py-3">License</th><th className="px-5 py-3">Package</th><th className="px-5 py-3">Charged</th><th className="px-5 py-3">Duration</th><th className="px-5 py-3">Issued</th><th className="px-5 py-3">Validity</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((l) => <tr key={l.id}><td className="px-5 py-4"><div className="font-semibold">{l.customer_name}</div><div className="text-xs text-slate-400">{l.customer?.gstin || "GSTIN not recorded"} · {l.customer?.email || "No email"}</div></td><td className="px-5 py-4"><button onClick={() => copy(l.license_key)} className="inline-flex items-center gap-2 rounded-lg bg-slate-100 px-2.5 py-1.5 font-mono text-xs font-semibold">{l.license_key}<Copy size={13} /></button></td><td className="px-5 py-4">{l.package_name}</td><td className="px-5 py-4 font-semibold">{money(l.amount_charged)}</td><td className="px-5 py-4 text-slate-500">{l.validity_months || "—"} months</td><td className="px-5 py-4 text-slate-500">{formatDate(l.issued_at)}</td><td className="px-5 py-4 text-slate-500">{formatDate(l.expires_at)}</td><td className="px-5 py-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{l.status}</span></td><td className="px-5 py-4"><select value="" onChange={(e) => e.target.value && changeStatus(l, e.target.value)} className="rounded-lg border border-slate-200 bg-white px-2 py-1.5 text-xs"><option value="">Action</option><option value="active">Activate</option><option value="suspended">Suspend</option><option value="revoked">Revoke</option></select></td></tr>)}{!filtered.length && <tr><td colSpan="9" className="px-5 py-12 text-center text-slate-400">{loading ? "Loading licensing server…" : "No licenses found."}</td></tr>}</tbody></table></div></section>
    {created && <div className="fixed inset-x-4 bottom-5 z-50 mx-auto max-w-3xl rounded-2xl border border-emerald-200 bg-white p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-emerald-600">License Generated</p><h3 className="mt-1 font-bold">{created.customer_name}</h3><p className="text-sm text-slate-500">{created.package_name} · {created.validity_months} months · {money(created.amount_charged)}</p></div><button onClick={() => setCreated(null)} className="text-slate-400">×</button></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-slate-950 p-3"><code className="flex-1 break-all text-sm font-bold tracking-wider text-white">{created.license_key}</code><button onClick={() => copy(created.license_key)} className="rounded-lg bg-white/10 p-2 text-white"><Copy size={16} /></button></div><div className="mt-4 grid gap-3 text-xs text-slate-600 sm:grid-cols-3"><div><b>Issued:</b> {formatDate(created.issued_at)}</div><div><b>Expires:</b> {formatDate(created.expires_at)}</div><div><b>GSTIN:</b> {created.customer?.gstin || "—"}</div></div></div>}
    {showCreate && <div className="fixed inset-0 z-40 flex items-center justify-center overflow-y-auto bg-slate-950/40 p-4"><form onSubmit={submit} className="my-6 w-full max-w-4xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Generate Commercial License</h2><p className="mt-1 text-sm text-slate-500">Capture the complete customer, billing and license record in one workflow.</p></div><button type="button" onClick={() => setShowCreate(false)} className="text-slate-400">×</button></div>
      <div className="mt-6 rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="mb-3 flex items-center gap-2 font-semibold text-slate-800"><Building2 size={17} /> Customer & GST details</div><div className="grid gap-4 md:grid-cols-2"><Field label="Company Name *"><Input required value={form.company_name} onChange={(e) => setForm({ ...form, company_name: e.target.value })} placeholder="Registered company / firm name" /></Field><Field label="Contact Person"><Input value={form.contact_name} onChange={(e) => setForm({ ...form, contact_name: e.target.value })} /></Field><Field label="Email *"><Input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Phone"><Input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field><Field label="GSTIN"><Input value={form.gstin} onChange={(e) => setForm({ ...form, gstin: e.target.value.toUpperCase() })} placeholder="15-character GSTIN" /></Field><Field label="Pincode"><Input value={form.pincode} onChange={(e) => setForm({ ...form, pincode: e.target.value })} /></Field><Field label="City"><Input value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></Field><Field label="State"><Input value={form.state} onChange={(e) => setForm({ ...form, state: e.target.value })} /></Field><Field label="Registered Address" className="md:col-span-2"><textarea value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} rows="2" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-slate-400" /></Field><Field label="GST Address" className="md:col-span-2"><textarea value={form.gst_address} onChange={(e) => setForm({ ...form, gst_address: e.target.value })} rows="2" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-none focus:border-slate-400" placeholder="If different from registered address" /></Field></div></div>
      <div className="mt-4 rounded-2xl border border-slate-100 bg-white p-4"><div className="mb-3 flex items-center gap-2 font-semibold text-slate-800"><KeyRound size={17} /> License & commercial terms</div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Field label="Package"><select value={form.package_id} onChange={(e) => packageChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5"><option value="essential">Essential — Tasks + Invoicing</option><option value="professional">Professional — Tasks + Invoicing + HRMS</option><option value="enterprise">Enterprise — Tasks + Invoicing + Accounting + HRMS</option></select></Field><Field label="Months *"><Input required type="number" min="1" value={form.validity_months} onChange={(e) => setForm({ ...form, validity_months: e.target.value })} /></Field><Field label="Amount Charged (₹)"><Input type="number" min="0" step="0.01" value={form.amount_charged} onChange={(e) => setForm({ ...form, amount_charged: e.target.value })} /></Field><Field label="Maximum Users"><Input required type="number" min="1" value={form.max_users} onChange={(e) => setForm({ ...form, max_users: Number(e.target.value) })} /></Field><Field label="Maximum Installations"><Input required type="number" min="1" value={form.max_installations} onChange={(e) => setForm({ ...form, max_installations: Number(e.target.value) })} /></Field><Field label="Currency"><Input value={form.currency} onChange={(e) => setForm({ ...form, currency: e.target.value.toUpperCase() })} /></Field><Field label="Notes" className="md:col-span-2"><Input value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="Payment reference, special terms, etc." /></Field></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-500"><span className="inline-flex items-center gap-1"><CalendarDays size={14} /> Issued automatically on generation</span><span className="inline-flex items-center gap-1"><IndianRupee size={14} /> Amount stored with the license</span><span className="inline-flex items-center gap-1"><Users size={14} /> User limit enforced during onboarding</span></div></div>
      <div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setShowCreate(false)} className="rounded-xl border px-4 py-2.5 text-sm font-semibold">Cancel</button><button type="submit" className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Generate License & Customer</button></div>
    </form></div>}
  </div></div>;
}
