import React, { useEffect, useMemo, useState } from "react";
import {
  ArrowDown, ArrowUp, Blocks, Check, ChevronLeft, Copy, Eye, Globe2, ImagePlus,
  LayoutTemplate, Menu, Monitor, Palette, Plus, Redo2, Save, Search, Settings2,
  Smartphone, Sparkles, Store, Trash2, Undo2, Upload, Users, Video, X, Zap
} from "lucide-react";
import { toast } from "sonner";
import { getAdminWebsiteConfig, resetWebsiteConfig, saveWebsiteConfig } from "@/lib/websiteApi";

const clone = (v) => JSON.parse(JSON.stringify(v));
const id = (p = "item") => `${p}_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;
const DEFAULT_BUILDER = {
  version: 2, activePageId: "home",
  pages: [
    { id: "home", name: "Home", slug: "/", visible: true, sections: [
      { id: "hero", type: "hero", title: "Hero", visible: true, data: { badge: "The modern business operating system", title: "Run your entire business from one intelligent workspace.", subtitle: "Task management, invoicing, accounting, HRMS and compliance — connected in one platform.", primaryText: "Explore Taskosphere", primaryHref: "#features", secondaryText: "Sign in", secondaryHref: "/login", image: "/logo-transparent.png", align: "left" } },
      { id: "features", type: "features", title: "Features", visible: true, data: { heading: "Everything your team needs", subtitle: "Build the exact commercial package your customer needs.", items: [
        { title: "Task Management", description: "Projects, tasks, workflows and reminders.", icon: "check" },
        { title: "Invoicing", description: "Quotations, invoices and customer billing.", icon: "receipt" },
        { title: "Accounting", description: "Ledgers, banking and financial reports.", icon: "landmark" },
        { title: "HRMS", description: "People, attendance, leave and recruitment.", icon: "users" },
        { title: "Compliance", description: "GST, ROC, trademark and compliance workflows.", icon: "shield" },
        { title: "AI & Automation", description: "Document processing and operational assistance.", icon: "sparkles" }
      ] } },
      { id: "pricing", type: "pricing", title: "Pricing", visible: true, data: { heading: "Simple commercial packaging", subtitle: "Choose the package that fits your business.", items: [
        { name: "Essential", price: "Custom", period: "per business", description: "Tasks + Invoicing", featured: false },
        { name: "Professional", price: "Custom", period: "per business", description: "Tasks + Invoicing + HRMS", featured: true },
        { name: "Enterprise", price: "Custom", period: "per business", description: "Tasks + Invoicing + Accounting + HRMS", featured: false }
      ] } },
      { id: "cta", type: "cta", title: "Call to action", visible: true, data: { heading: "Ready to make your software feel like your own brand?", text: "Configure your platform from the Master Console.", button: "Get started", href: "/login" } }
    ] },
    { id: "about", name: "About", slug: "/about", visible: true, sections: [{ id: "about-content", type: "content", title: "About", visible: true, data: { heading: "About your business", body: "Tell visitors what you do, why you do it and who you serve." } }] },
    { id: "contact", name: "Contact", slug: "/contact", visible: true, sections: [{ id: "contact-form", type: "form", title: "Contact form", visible: true, data: { heading: "Let's talk", body: "Send us a message and our team will get back to you." } }] }
  ],
  global: { header: { sticky: true, showLogin: true }, footer: { showSocial: true }, container: "wide", radius: "large", animation: "subtle", mobileMenu: "drawer" },
  seo: { sitemap: true, robots: "index,follow", schema: true },
  integrations: { googleAnalytics: "", metaPixel: "", customHead: "", customBody: "" },
  marketing: { cookieBanner: false, whatsapp: true, chat: false, popup: false },
  localization: { defaultLanguage: "English", languages: ["English"] },
  modules: { Blog: false, "Online Store": false, Bookings: false, "Forms & Leads": true, Portfolio: false, Events: false, Jobs: false, Donations: false, Courses: false, Multilingual: false, "Email Marketing": false, Analytics: false }
};

const WIDGETS = [
  ["text", "Text", "Text content"], ["heading", "Heading", "Section heading"], ["image", "Image", "Image block"], ["button", "Button", "Call-to-action"],
  ["gallery", "Gallery", "Image gallery"], ["video", "Video", "Video block"], ["divider", "Divider", "Visual separator"], ["form", "Contact Form", "Lead form"],
  ["map", "Map", "Location block"], ["pricing", "Pricing", "Pricing cards"], ["testimonials", "Testimonials", "Customer quotes"], ["faq", "FAQ", "Questions & answers"]
];
const APPS = [
  ["Blog", "Articles, categories, writers and SEO", Store], ["Online Store", "Products, carts and orders", Store], ["Bookings", "Appointments and availability", LayoutTemplate],
  ["Forms & Leads", "Forms and lead capture", Users], ["Portfolio", "Projects and case studies", ImagePlus], ["Events", "Registration and attendees", LayoutTemplate],
  ["Jobs", "Vacancies and applications", Users], ["Multilingual", "Languages and localized SEO", Globe2], ["Analytics", "Traffic and conversion insights", Sparkles]
];

function Field({ label, value, onChange, multiline = false, placeholder = "" }) {
  const Tag = multiline ? "textarea" : "input";
  return <label className="block"><span className="text-xs font-bold text-slate-600">{label}</span><Tag value={value ?? ""} placeholder={placeholder} rows={multiline ? 5 : undefined} onChange={(e) => onChange(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-slate-400 focus:ring-2 focus:ring-slate-100" /></label>;
}
function Toggle({ label, checked, onChange }) { return <label className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 p-3 text-sm font-semibold"><span>{label}</span><input type="checkbox" checked={!!checked} onChange={(e) => onChange(e.target.checked)} /></label>; }
function ToolButton({ icon: Icon, children, onClick, active = false, disabled = false }) { return <button type="button" onClick={onClick} disabled={disabled} className={`inline-flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-bold ${active ? "bg-slate-950 text-white" : "text-slate-600 hover:bg-slate-100"} disabled:opacity-40`}><Icon size={15}/>{children}</button>; }

function Preview({ section, config }) {
  const d = section.data || {}; const primary = config.primary_color || "#0D3B66"; const accent = config.accent_color || "#1FAF5A";
  if (section.type === "hero") return <div className="rounded-2xl p-8 text-white" style={{ background: `linear-gradient(135deg, ${primary}, #061827)` }}><div className="grid gap-7 md:grid-cols-2"><div><span className="inline-flex rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase">{d.badge || "Badge"}</span><h2 className="mt-4 text-3xl font-black">{d.title || "Your headline"}</h2><p className="mt-4 text-sm leading-6 text-white/70">{d.subtitle}</p><div className="mt-5 flex gap-2"><span className="rounded-lg px-4 py-2 text-xs font-bold" style={{ background: accent }}>{d.primaryText || "Get started"}</span><span className="rounded-lg border border-white/20 px-4 py-2 text-xs font-bold">{d.secondaryText || "Learn more"}</span></div></div><div className="flex min-h-44 items-center justify-center rounded-2xl bg-white/10 p-4">{d.image ? <img src={d.image} alt="" className="max-h-44 max-w-full object-contain"/> : <ImagePlus size={42} className="text-white/30"/>}</div></div></div>;
  if (section.type === "features") return <div className="rounded-2xl border border-slate-200 bg-white p-7"><p className="text-[10px] font-bold uppercase" style={{ color: accent }}>Platform</p><h2 className="mt-2 text-2xl font-black">{d.heading || "Features"}</h2><p className="mt-2 text-sm text-slate-500">{d.subtitle}</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(d.items || []).map((x, i) => <div key={i} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="h-8 w-8 rounded-lg" style={{ background: `${accent}20` }}/><h3 className="mt-3 text-sm font-bold">{x.title}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{x.description}</p></div>)}</div></div>;
  if (section.type === "pricing") return <div className="rounded-2xl bg-slate-50 p-7"><h2 className="text-2xl font-black">{d.heading || "Pricing"}</h2><p className="mt-2 text-sm text-slate-500">{d.subtitle}</p><div className="mt-6 grid gap-3 md:grid-cols-3">{(d.items || []).map((x, i) => <div key={i} className={`rounded-xl border p-5 ${x.featured ? "text-white" : "bg-white"}`} style={x.featured ? { background: primary, borderColor: primary } : { borderColor: "#e2e8f0" }}><b>{x.name}</b><div className="mt-3 text-2xl font-black">{x.price}</div><div className="text-xs opacity-60">{x.period}</div><p className="mt-3 text-xs opacity-70">{x.description}</p></div>)}</div></div>;
  if (section.type === "cta") return <div className="rounded-2xl p-8 text-white" style={{ background: `linear-gradient(135deg, ${primary}, #061827)` }}><h2 className="text-2xl font-black">{d.heading}</h2><p className="mt-3 max-w-2xl text-sm text-white/70">{d.text}</p><span className="mt-5 inline-flex rounded-lg bg-white px-4 py-2 text-xs font-bold text-slate-900">{d.button || "Get started"}</span></div>;
  if (["content", "text", "heading"].includes(section.type)) return <div className="rounded-2xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-black">{d.heading || "Content"}</h2><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-600">{d.body || d.subtitle}</p></div>;
  if (section.type === "image") return <div className="rounded-2xl border border-slate-200 bg-white p-5"><img src={d.src} alt={d.alt || ""} className="max-h-80 w-full rounded-xl object-cover"/></div>;
  if (section.type === "video") return <div className="flex h-56 items-center justify-center rounded-2xl bg-slate-950 text-white"><Video size={32}/><span className="ml-3 text-sm font-bold">{d.url || "Video"}</span></div>;
  if (section.type === "form") return <div className="rounded-2xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-black">{d.heading || "Contact us"}</h2><p className="mt-2 text-sm text-slate-500">{d.body}</p><div className="mt-5 grid gap-3 md:grid-cols-2"><div className="h-10 rounded-lg bg-slate-100"/><div className="h-10 rounded-lg bg-slate-100"/><div className="h-24 rounded-lg bg-slate-100 md:col-span-2"/></div></div>;
  if (section.type === "faq") return <div className="rounded-2xl border border-slate-200 bg-white p-7"><h2 className="text-2xl font-black">{d.heading || "Frequently asked questions"}</h2><div className="mt-5 space-y-2">{[1,2,3].map((x)=><div key={x} className="rounded-xl border border-slate-100 p-4 text-sm font-bold">Question {x}<span className="float-right">+</span></div>)}</div></div>;
  if (section.type === "divider") return <div className="py-5"><div className="h-px bg-slate-200"/></div>;
  return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-400">{section.title || section.type}</div>;
}

function makeBuilder(config) { const b = config?.builder; if (b?.pages?.length) return b; return clone(DEFAULT_BUILDER); }
function addSection(type) {
  const data = { heading: "New section", body: "Add your content here." };
  if (type === "hero") Object.assign(data, { badge: "New", title: "Your headline", subtitle: "Supporting message", primaryText: "Get started", primaryHref: "/login", secondaryText: "Learn more", secondaryHref: "#" });
  if (type === "features") Object.assign(data, { heading: "Features", subtitle: "Showcase your capabilities", items: [{ title: "Feature", description: "Describe this feature", icon: "sparkles" }] });
  if (type === "pricing") Object.assign(data, { heading: "Pricing", subtitle: "Choose your plan", items: [{ name: "Plan", price: "Custom", period: "per month", description: "Plan details", featured: false }] });
  if (type === "cta") Object.assign(data, { heading: "Ready to get started?", text: "Tell customers what to do next.", button: "Get started", href: "/login" });
  if (type === "image") Object.assign(data, { src: "/logo-transparent.png", alt: "" });
  if (type === "video") Object.assign(data, { url: "" });
  return { id: id(type), type, title: type[0].toUpperCase() + type.slice(1), visible: true, data };
}

export default function WebsiteBuilder() {
  const [config, setConfig] = useState(null), [builder, setBuilder] = useState(null), [panel, setPanel] = useState("pages"), [device, setDevice] = useState("desktop");
  const [selectedSectionId, setSelectedSectionId] = useState(null), [history, setHistory] = useState([]), [future, setFuture] = useState([]), [showPreview, setShowPreview] = useState(false), [saving, setSaving] = useState(false), [search, setSearch] = useState("");
  useEffect(() => { getAdminWebsiteConfig().then((data) => { setConfig(data); const b = makeBuilder(data); setBuilder(b); setSelectedSectionId(b.pages.find((p) => p.id === b.activePageId)?.sections?.[0]?.id || b.pages[0]?.sections?.[0]?.id || null); }).catch((e) => toast.error(e?.response?.data?.detail || "Unable to load website builder.")); }, []);
  const page = useMemo(() => builder?.pages?.find((p) => p.id === builder?.activePageId) || builder?.pages?.[0], [builder]);
  const selected = page?.sections?.find((s) => s.id === selectedSectionId) || null;
  const commit = (next) => { setHistory((h) => [...h.slice(-29), clone(builder)]); setFuture([]); setBuilder(next); };
  const updateBuilder = (fn) => { const next = clone(builder); fn(next); commit(next); };
  const updateSection = (patch) => updateBuilder((b) => { const p = b.pages.find((x) => x.id === b.activePageId); const s = p?.sections.find((x) => x.id === selectedSectionId); if (s) Object.assign(s, patch); });
  const updateData = (key, value) => updateBuilder((b) => { const p = b.pages.find((x) => x.id === b.activePageId); const s = p?.sections.find((x) => x.id === selectedSectionId); if (s) s.data[key] = value; });
  const add = (type) => { const section = addSection(type); updateBuilder((b) => b.pages.find((x) => x.id === b.activePageId).sections.push(section)); setSelectedSectionId(section.id); setPanel("pages"); };
  const move = (direction) => updateBuilder((b) => { const p = b.pages.find((x) => x.id === b.activePageId); const i = p.sections.findIndex((x) => x.id === selectedSectionId); const j = direction === "up" ? i - 1 : i + 1; if (i >= 0 && j >= 0 && j < p.sections.length) [p.sections[i], p.sections[j]] = [p.sections[j], p.sections[i]]; });
  const duplicate = () => { if (!selected) return; const copy = clone(selected); copy.id = id("section"); copy.title = `${copy.title} copy`; updateBuilder((b) => { const p = b.pages.find((x) => x.id === b.activePageId); const i = p.sections.findIndex((x) => x.id === selectedSectionId); p.sections.splice(i + 1, 0, copy); }); setSelectedSectionId(copy.id); };
  const remove = () => { if (!selected || !window.confirm("Delete this section?")) return; updateBuilder((b) => { const p = b.pages.find((x) => x.id === b.activePageId); p.sections = p.sections.filter((s) => s.id !== selectedSectionId); }); setSelectedSectionId(page?.sections?.find((s) => s.id !== selectedSectionId)?.id || null); };
  const addPage = () => { const p = { id: id("page"), name: "New Page", slug: `/page-${Date.now()}`, visible: true, sections: [addSection("content")] }; updateBuilder((b) => b.pages.push(p)); setBuilder((b) => ({ ...b, activePageId: p.id })); setSelectedSectionId(p.sections[0].id); };
  const undo = () => { const previous = history.at(-1); if (!previous) return; setFuture((f) => [clone(builder), ...f]); setHistory((h) => h.slice(0, -1)); setBuilder(previous); setSelectedSectionId(previous.pages.find((p) => p.id === previous.activePageId)?.sections?.[0]?.id || null); };
  const redo = () => { const next = future[0]; if (!next) return; setHistory((h) => [...h, clone(builder)]); setFuture((f) => f.slice(1)); setBuilder(next); };
  const publish = async () => { if (!config || !builder) return; setSaving(true); try { const saved = await saveWebsiteConfig({ ...config, builder }); setConfig(saved); toast.success("Website published successfully."); } catch (e) { toast.error(e?.response?.data?.detail || "Unable to publish website."); } finally { setSaving(false); } };
  const reset = async () => { if (!window.confirm("Reset website content and builder to defaults?")) return; try { const data = await resetWebsiteConfig(); setConfig(data); const b = makeBuilder(data); setBuilder(b); setSelectedSectionId(b.pages[0].sections[0].id); setHistory([]); setFuture([]); toast.success("Website reset."); } catch (e) { toast.error(e?.response?.data?.detail || "Unable to reset website."); } };
  if (!config || !builder || !page) return <div className="min-h-screen bg-slate-50 p-8"><div className="rounded-3xl border border-slate-200 bg-white p-10 text-center text-slate-400">Loading Website Builder…</div></div>;
  const navPages = builder.pages.filter((p) => p.visible !== false);
  const inspector = selected ? <div className="space-y-4"><Field label="Section name" value={selected.title} onChange={(v) => updateSection({ title: v })}/><Field label="Section type" value={selected.type} onChange={(v) => updateSection({ type: v })}/>{["content","text","heading","faq","form","cta"].includes(selected.type) && <><Field label="Heading" value={selected.data.heading} onChange={(v) => updateData("heading", v)}/><Field label="Body" value={selected.data.body || selected.data.text} onChange={(v) => updateData(selected.type === "content" ? "body" : "body", v)} multiline/></>}{selected.type === "hero" && <><Field label="Badge" value={selected.data.badge} onChange={(v) => updateData("badge", v)}/><Field label="Headline" value={selected.data.title} onChange={(v) => updateData("title", v)} multiline/><Field label="Subtitle" value={selected.data.subtitle} onChange={(v) => updateData("subtitle", v)} multiline/><Field label="Primary button" value={selected.data.primaryText} onChange={(v) => updateData("primaryText", v)}/><Field label="Primary link" value={selected.data.primaryHref} onChange={(v) => updateData("primaryHref", v)}/><Field label="Image URL" value={selected.data.image} onChange={(v) => updateData("image", v)}/></>}{selected.type === "image" && <><Field label="Image URL" value={selected.data.src} onChange={(v) => updateData("src", v)}/><Field label="Alt text" value={selected.data.alt} onChange={(v) => updateData("alt", v)}/></>}{selected.type === "video" && <Field label="Video URL" value={selected.data.url} onChange={(v) => updateData("url", v)}/>}<Toggle label="Show section" checked={selected.visible !== false} onChange={(v) => updateSection({ visible: v })}/></div> : <div className="rounded-xl bg-slate-50 p-4 text-xs text-slate-400">Select a section to edit its content.</div>;
  return <div className="flex h-[calc(100vh-118px)] min-h-[720px] flex-col overflow-hidden bg-slate-100 text-slate-900">
    <header className="flex h-14 shrink-0 items-center justify-between border-b border-slate-200 bg-white px-3 shadow-sm"><div className="flex items-center gap-2"><ToolButton icon={ChevronLeft} onClick={() => window.history.back()}>Back</ToolButton><div className="hidden border-l border-slate-200 pl-3 md:block"><div className="text-sm font-black">Website Builder</div><div className="text-[10px] text-slate-400">SITE123-style visual editor</div></div></div><div className="flex items-center gap-1"><ToolButton icon={Undo2} onClick={undo} disabled={!history.length}/><ToolButton icon={Redo2} onClick={redo} disabled={!future.length}/><span className="mx-1 h-6 w-px bg-slate-200"/><ToolButton icon={Monitor} active={device === "desktop"} onClick={() => setDevice("desktop")}>Desktop</ToolButton><ToolButton icon={Smartphone} active={device === "mobile"} onClick={() => setDevice("mobile")}>Mobile</ToolButton></div><div className="flex items-center gap-2"><ToolButton icon={Eye} onClick={() => setShowPreview(true)}>Preview</ToolButton><button type="button" onClick={publish} disabled={saving} className="inline-flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2 text-xs font-bold text-white disabled:opacity-50"><Save size={15}/>{saving ? "Publishing…" : "Publish"}</button></div></header>
    <div className="flex min-h-0 flex-1"><aside className="flex w-[255px] shrink-0 flex-col border-r border-slate-200 bg-white"><div className="grid grid-cols-4 border-b border-slate-200 p-1">{[[Menu,"pages"],[Palette,"design"],[Blocks,"apps"],[Settings2,"settings"]].map(([Icon, name]) => <button type="button" key={name} onClick={() => setPanel(name)} className={`flex flex-col items-center gap-1 rounded-lg py-2 text-[10px] font-bold ${panel === name ? "bg-slate-950 text-white" : "text-slate-500 hover:bg-slate-100"}`}><Icon size={15}/>{name}</button>)}</div><div className="min-h-0 flex-1 overflow-auto p-3">
      {panel === "pages" && <><div className="mb-3 flex items-center justify-between"><span className="text-xs font-black uppercase tracking-wider text-slate-400">Pages</span><button type="button" onClick={addPage} className="rounded-lg bg-slate-950 p-1.5 text-white"><Plus size={14}/></button></div>{navPages.map((p) => <div key={p.id} className={`mb-2 rounded-xl border ${p.id === builder.activePageId ? "border-slate-900 bg-slate-50" : "border-slate-200"}`}><button type="button" onClick={() => { setBuilder((b) => ({ ...b, activePageId: p.id })); setSelectedSectionId(p.sections[0]?.id || null); }} className="flex w-full items-center gap-2 px-3 py-2.5 text-left"><Menu size={13} className="text-slate-300"/><span className="flex-1 text-sm font-bold">{p.name}</span></button>{p.id === builder.activePageId && <div className="border-t border-slate-200 p-2">{p.sections.map((s) => <button type="button" key={s.id} onClick={() => setSelectedSectionId(s.id)} className={`mb-1 flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-left text-xs ${s.id === selectedSectionId ? "bg-slate-950 text-white" : "text-slate-600 hover:bg-slate-100"}`}><LayoutTemplate size={13}/>{s.title}</button>)}</div>}</div>)}<button type="button" onClick={() => setPanel("add")} className="mt-2 flex w-full items-center gap-2 rounded-xl border border-dashed border-slate-300 px-3 py-3 text-xs font-bold text-slate-500"><Plus size={14}/> Add section</button></>}
      {panel === "add" && <><div className="mb-3 text-xs font-black uppercase tracking-wider text-slate-400">Content blocks</div>{WIDGETS.map(([type, name, desc]) => <button type="button" key={type} onClick={() => add(type)} className="mb-2 flex w-full items-start gap-2 rounded-xl border border-slate-200 p-3 text-left hover:bg-slate-50"><Zap size={14} className="mt-0.5"/><span><b className="block text-xs">{name}</b><span className="text-[10px] text-slate-400">{desc}</span></span></button>)}</>}
      {panel === "apps" && <><div className="mb-3 text-xs font-black uppercase tracking-wider text-slate-400">Apps & modules</div><div className="relative mb-3"><Search size={14} className="absolute left-3 top-2.5 text-slate-400"/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search modules" className="w-full rounded-lg border border-slate-200 py-2 pl-9 pr-3 text-xs"/></div>{APPS.filter(([n]) => n.toLowerCase().includes(search.toLowerCase())).map(([name, desc, Icon]) => <button type="button" key={name} onClick={() => { updateBuilder((b) => { b.modules[name] = true; }); toast.success(`${name} module enabled.`); }} className="mb-2 flex w-full items-start gap-2 rounded-xl border border-slate-200 p-3 text-left"><Icon size={15}/><span><b className="block text-xs">{name}</b><span className="text-[10px] text-slate-400">{desc}</span></span></button>)}</>}
      {panel === "design" && <div className="space-y-3"><div className="text-xs font-black uppercase tracking-wider text-slate-400">Design system</div><Toggle label="Sticky header" checked={builder.global?.header?.sticky} onChange={(v) => updateBuilder((b) => { b.global.header.sticky = v; })}/><Toggle label="Show sign in" checked={builder.global?.header?.showLogin} onChange={(v) => updateBuilder((b) => { b.global.header.showLogin = v; })}/><Field label="Container" value={builder.global?.container} onChange={(v) => updateBuilder((b) => { b.global.container = v; })}/><Field label="Corner radius" value={builder.global?.radius} onChange={(v) => updateBuilder((b) => { b.global.radius = v; })}/></div>}
      {panel === "settings" && <div className="space-y-3"><div className="text-xs font-black uppercase tracking-wider text-slate-400">Website settings</div><Toggle label="Sitemap" checked={builder.seo?.sitemap} onChange={(v) => updateBuilder((b) => { b.seo.sitemap = v; })}/><Toggle label="Structured data" checked={builder.seo?.schema} onChange={(v) => updateBuilder((b) => { b.seo.schema = v; })}/><Field label="Robots" value={builder.seo?.robots} onChange={(v) => updateBuilder((b) => { b.seo.robots = v; })}/><Field label="Google Analytics ID" value={builder.integrations?.googleAnalytics} onChange={(v) => updateBuilder((b) => { b.integrations.googleAnalytics = v; })}/><Field label="Custom head" value={builder.integrations?.customHead} onChange={(v) => updateBuilder((b) => { b.integrations.customHead = v; })} multiline/></div>}
    </div></aside><main className="min-w-0 flex-1 overflow-auto bg-slate-100"><div className="flex min-h-full justify-center p-5 lg:p-8"><div className={`w-full transition-all ${device === "mobile" ? "max-w-[390px]" : "max-w-[1100px]"}`}><div className="mb-3 flex items-center justify-between text-xs text-slate-400"><span>{page.name} · {page.slug}</span><span>{device === "mobile" ? "Mobile view" : "Desktop view"}</span></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xl"><div className="border-b border-slate-100 px-6 py-4"><div className="flex items-center gap-3"><img src={config.logo_url || "/logo.png"} alt="" className="h-7 w-auto"/><div className="text-xs font-bold">{config.site_name}</div></div></div><div className="space-y-3 bg-slate-50 p-3">{page.sections.filter((s) => s.visible !== false).map((s) => <div key={s.id} onClick={() => setSelectedSectionId(s.id)} className={`relative cursor-pointer rounded-2xl ${s.id === selectedSectionId ? "ring-2 ring-slate-950 ring-offset-2" : "hover:ring-1 hover:ring-slate-300"}`}><Preview section={s} config={config}/>{s.id === selectedSectionId && <div className="absolute right-3 top-3 flex gap-1 rounded-lg bg-slate-950 p-1 shadow-lg"><button type="button" onClick={(e) => { e.stopPropagation(); move("up"); }} className="p-1 text-white"><ArrowUp size={13}/></button><button type="button" onClick={(e) => { e.stopPropagation(); move("down"); }} className="p-1 text-white"><ArrowDown size={13}/></button><button type="button" onClick={(e) => { e.stopPropagation(); duplicate(); }} className="p-1 text-white"><Copy size={13}/></button><button type="button" onClick={(e) => { e.stopPropagation(); remove(); }} className="p-1 text-white"><Trash2 size={13}/></button></div>}</div>)}</div><button type="button" onClick={() => setPanel("add")} className="m-3 flex w-[calc(100%-1.5rem)] items-center justify-center gap-2 rounded-xl border border-dashed border-slate-300 bg-white py-4 text-xs font-bold text-slate-500"><Plus size={14}/> Add section</button></div></div></div></main><aside className="hidden w-[315px] shrink-0 border-l border-slate-200 bg-white xl:flex xl:flex-col"><div className="border-b border-slate-200 px-4 py-3"><div className="text-xs font-black uppercase tracking-wider text-slate-400">Inspector</div><div className="mt-1 text-sm font-black">{selected?.title || "Select a section"}</div></div><div className="min-h-0 flex-1 overflow-auto p-4">{inspector}</div><div className="border-t border-slate-200 p-3"><div className="grid grid-cols-2 gap-2"><ToolButton icon={ArrowUp} onClick={() => move("up")}>Up</ToolButton><ToolButton icon={ArrowDown} onClick={() => move("down")}>Down</ToolButton><ToolButton icon={Copy} onClick={duplicate}>Duplicate</ToolButton><ToolButton icon={Trash2} onClick={remove}>Delete</ToolButton></div></div></aside></div>
    {showPreview && <div className="fixed inset-0 z-[100] bg-slate-950/70 p-4"><div className="mx-auto flex h-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white"><div className="flex items-center justify-between border-b px-4 py-3"><b>Live Website Preview</b><button type="button" onClick={() => setShowPreview(false)} className="rounded-lg p-2 hover:bg-slate-100"><X size={18}/></button></div><div className="min-h-0 flex-1 overflow-auto p-5"><div className="mx-auto max-w-5xl space-y-3">{page.sections.filter((s) => s.visible !== false).map((s) => <Preview key={s.id} section={s} config={config}/>)}</div></div></div></div>}
  </div>;
}
